### ISSUE TITLE
Do you use the experimental association-tracking feature?

### ISSUE THREAD

**Issue by jaredbeck** [paper-trail-gem/paper_trail#1070]
Association tracking is an *endangered* feature. For the past three or four years it has been an *experimental* feature, not recommended for production. It has a long list of [known issues](https://github.com/airblade/paper_trail#4b1-known-issues) and has no regular volunteers caring for it.

If you use this experimental feature, react with 👍 

If you want to volunteer to care for it, please comment below.

If we can't make a serious dent in the list of known issues over the next few years, then I'm inclined to delete it, though that would make me sad because I've put dozens of hours into it, and I know others have too.

**Comment by jaredbeck** [comment]
If you are using this endangered feature, please subscribe to this issue. If no one volunteers to take care of this feature, then its deprecation and eventual deletion will be announced here.

**Comment by westonganger** [comment]
I think it is a bad idea to remove this feature even without maintainers. There is currently no other gem that provides this functionality. Removing it would be a shame to the Rails community and will also limit people who wish to upgrade to newer versions. However if it could be extracted into a separate gem ie. `paper_trail_association_tracking` that would be a good idea.

**Comment by jaredbeck** [comment]
> However if it could be extracted into a separate gem ie. paper_trail_association_tracking that would be a good idea.

It should be possible. You've made some contributions recently, Weston, would you like to maintain it? I can help you extract the gem if you want to pair on it.

**Comment by westonganger** [comment]
Yeah I think I could probably swing that. To be honest though, I don't really know anything about the code behind the feature however I'm sure during extraction into a gem I will start to get a feel for a majority of it. So after its been extracted, I probably wouldn't be making many major contributions myself to the code other than maintainer stuff. As issues and PR's roll in I'll start to have more to say in how it goes down though.

Please provide some insight on where to start looking and tinkering.

**Comment by jaredbeck** [comment]
> Please provide some insight on where to start looking and tinkering.

Great! Can you pair with me on it over screen-share? Please email me jared at jaredbeck dot com. Thanks.

**Comment by westonganger** [comment]
I spent a bit of time tonight getting this repo started: https://github.com/westonganger/paper_trail_associations_tracking 

- I started by copying this repo and removed most of the paper_trail only stuff. 
- See the TODO section in the readme for the current task list

**Comment by jaredbeck** [comment]
>> .. if it could be extracted into a separate gem ..

> I spent a bit of time tonight getting this repo started: https://github.com/westonganger/paper_trail_associations_tracking I started by copying this repo and removed most of the paper_trail only stuff.
   
That sounds like a good approach. I am picturing the following milestones:

1. `paper_trail` gemspec has a runtime dependency on the new gem for a year or so, and keeps all existing tests.
2. `paper_trail` gemspec has a development dependency on the new gem for a year or so, and keeps all existing tests.
3. Eventually, `paper_trail` does not depend on or test the new gem
 
Regarding the gem name, `paper_trail-associations_tracking` is the recommended punctuation, per the rubygems.org [Name your gem](https://guides.rubygems.org/name-your-gem/) guide.

**Comment by jaredbeck** [comment]
Closed via https://github.com/paper-trail-gem/paper_trail/pull/1103. Will release as 9.2.0
