### ISSUE TITLE
Pretty Print Changes in Console

### ISSUE THREAD

**Issue by whitslar** [paper-trail-gem/paper_trail#1083]
Would anyone be interested in a PR for pretty printing all changes of a Papertrail tracked object to the console? It would pull in the Hirb gem as a dependency... We've been using it quite a bit :) Here's a screenshot https://imgur.com/ehJhJHn

Haven't decided on a method name, maybe pp_versions

**Comment by jaredbeck** [comment]
> Would anyone be interested in a PR for pretty printing all changes of a Papertrail tracked object to the console? It would pull in the Hirb gem as a dependency... We've been using it quite a bit :) Here's a screenshot https://imgur.com/ehJhJHn

The screenshot looks nice, and this feature would be useful. It's not something I want in PT itself, but I'd be happy to help you create a separate gem for it. We can mention it in the docs, and the repo can be under the [paper-trail-gem organization](https://github.com/paper-trail-gem) if you want.
