### ISSUE TITLE
Paper Trail randomly return "nil" object when updating a model

### ISSUE THREAD

**Issue by rdudacz** [paper-trail-gem/paper_trail#1089]
It started when I updated the version of the gem from `8.1.2` to `9.0.0`.

I have noticed that after 

I have noticed (in the `versions` table) that there are "random" some `nil` records - "random" because the model has not been saved (or, for the record, the `edit` action/page hasn't been even visited), however, in the `versions` table are records like this:

The column **object** contains the following:
> id: 
> car_manufacturer_id: 
> owner: 
> mileage: 
> address: 
> country: 
> zip: 
> ...
There are basically listed all the attributes for the model - not with data, just empty.

The column **object_changes** contains the following:

> --- {}

In this modal (`car`), here's the paper_trail activation:

> has_paper_trail :meta => {car_id: :id}

What am I seeing these empty records in database (the form from the `edit` action, nor any other one, not been sent to the `update` action)?

**Comment by jaredbeck** [comment]
Thanks for the bug report. Per our [contributing guide][1] please use
our [bug report template][2].

[1]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://github.com/paper-trail-gem/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by jaredbeck** [comment]
The provided bug report produces this error:

```
ActiveModel::UnknownAttributeError: unknown attribute 'car_id' for PaperTrail::Version.
```

This is because, when you use `:meta => { car_id: :id }`, your `versions` table must have a `car_id` column.
