### ISSUE TITLE
Add Papertrail initializer option to switch PaperTrail::Reifiers::HasOne::FoundMoreThanOne for a warning instead

### ISSUE THREAD

**Issue by westonganger** [paper-trail-gem/paper_trail#1090]
After trying to upgrade from v8.1.2 to v9+. I started recieving this error `PaperTrail::Reifiers::HasOne::FoundMoreThanOne`. I believe the old paper trail just kinda said "I don't care about being totally correct, just carry on". So now I cannot upgrade because of this exception. Can we add an option to the initializer to instead just warn and continue.

https://github.com/paper-trail-gem/paper_trail/blob/06a5e30ab40581ee4f035989c961dd520f48e29a/lib/paper_trail/reifiers/has_one.rb#L77

We could change this to something like

```ruby
if PaperTrail.config.associations_just_warn_enabled
  # do warning
  versions.first
else
  # do raise
end
```

**Comment by jaredbeck** [comment]
I'm hesitant to add any more complexity related to association tracking. I'd like to see it have a dedicated maintainer and/or be extracted into a separate gem first. But, you're going to help with that, right? 🙏 

That said, I don't want to stop anyone from upgrading, so I guess we should add this configuration option. I'd call it `association_reify_error_behavior` and values can be `:warn` or `:error`. I think error should remain the default.

This should also be added to the [list of known issues](https://github.com/paper-trail-gem/paper_trail#4b1-known-issues) in the readme.

**Comment by westonganger** [comment]
Let me know if I should make a PR for this or if you are going to.

**Comment by jaredbeck** [comment]
> Let me know if I should make a PR for this or if you are going to.

Please go ahead. I don't use association tracking, so I don't have much motivation to work on it.
