### ISSUE TITLE
reify from specific date?

### ISSUE THREAD

**Issue by daniely** [paper-trail-gem/paper_trail#1100]
I need to know what an object looked like at a specific date. There doesn't seem to be a way to do this currently in papertrail so I'm planning on implementing it.

My question - is this a feature that would seem useful in paper-trail? If so I can submit a pull request when I'm done.

**Comment by batter** [comment]
What about the `version_at` method? I believe that is designed to serve this purpose, since it accepts a date or timestamp and then returns the re-ified object at that point in time.

**Comment by daniely** [comment]
Thanks! Didn't know about `version_at`. Perfect.
