### ISSUE TITLE
Whodunnit may sound confusing as it currently is

### ISSUE THREAD

**Issue by betosalvador** [paper-trail-gem/paper_trail#1116]
Hello guys

**Is your feature suggestion related to a problem? Please describe.**
I just found out that I've always used Whodunnit the wrong way.

I always thought Whodunnit was the user responsible for generating the current version being saved.

But I realized the truth Whodunnit is the subsequent user.

**Describe alternatives you've considered**
So my question is: should Papertrail not always save a copy of the last state of the object as the last version and configure the current user like Whodunnit?

Is there anyway to setup papertrail to work this way?
.
Thanks!

**Comment by jaredbeck** [comment]
> I just found out that I've always used Whodunnit the wrong way.

There's no wrong way to use the `whodunnit` column. Put whatever you want in there.

> I always thought Whodunnit was the user responsible for generating the current version being saved.

That is how most people use it.

> So my question is: should Papertrail not always save a copy of the last state of the object as the last version and configure the current user like Whodunnit?

I don't understand the question. From the docs:

> PaperTrail stores the pre-change version of the model ..
> https://github.com/paper-trail-gem/paper_trail#1c-basic-usage

**Comment by betosalvador** [comment]
Hello @jaredbeck

Thanks for response,

I realized that the method that I was looking for is "paper_trail_originator"

This method returns the user that "generated" a specific version.

The other thing that I looking for is how to save the live version as a "last version".

This will allow me to do a real time tracking with all interactions on a specific resource (including the last interaction).

For example, a Model "Article" that has a "status" attribute with values ("draft" and "published").

What that I want is: when any user update this Article (from "draft" to "published"), I should see a history of the interactions, like:
.
.
ARTICLE INTERACTIONS:

John ---- created ----- Status: draft ----------- 10 Jul 2018 08:25 PM
Anna ---- updated ---- Status: published ---- 12 Jul 2018 10:25 PM

THis kind of thing is possible?

thanks again

**Comment by betosalvador** [comment]
Summing up what I said above,

What I would like to do is to save the version after change.

That is, the last version saved, would always be a copy of the current object.

It is possible?

**Comment by jaredbeck** [comment]
> It is possible?

Per our [contributing guide][1], please ask usage questions on [StackOverflow][2].

Due to limited volunteer time, we can only accept bug reports and feature requests here on GitHub.

Once you create a question on StackOverflow, please feel free to comment here with the URL.

For instructions on how to file a bug report, please see our [issue template][3].

[1]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://stackoverflow.com/tags/paper-trail-gem
[3]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by betosalvador** [comment]
Hello @jaredbeck 

THanks and I'm sorry.

I will follow you advise.

thanks again!
