### ISSUE TITLE
PT 10

### ISSUE THREAD

**Issue by jaredbeck** [paper-trail-gem/paper_trail#1145]
@lorint and @seanlinsley is there anything else we need before releasing PT 10?

**Comment by romyhermawan96** [comment]
does paper trail works with mongoid?

i found [](https://github.com/kristianmandrup/papertrail_mongoid)

but its seems outdated

**Comment by jaredbeck** [comment]
>  jaredbeck deleted a comment from romyhermawan96

@romyhermawan96 please ask usage question on StackOverflow

**Comment by jaredbeck** [comment]
released
