### ISSUE TITLE
Attribute is changed but not logged

### ISSUE THREAD

**Issue by philsmy** [paper-trail-gem/paper_trail#1149]
I realise this is very vague but it's all we've got.

We are using paper_trail on a model:

 ```
class OrderItem < ApplicationRecord
  has_paper_trail only: [:item_id]
end
```

We are creating an object like this:
```
order_item = OrderItem.find_or_create_by(aoid: oi['OrderItemId']) do |newoi|
  newoi.item_id = product_item_id
end
```

As expected we end up with a single version in the "versions" for this object. In that version is the proper item_id.

But...the object does NOT have the specified product_item_id in the item_id field, it has a different id. We had hoped that paper_trail would help us track down how this is happening, but, somehow it is happening without a version being created.

Could this be because we have 
```
PaperTrail.config.track_associations = false
```
set?

We are using Rails 4.2.10 and PaperTrail 9.2.0

**Comment by jaredbeck** [comment]
Hi Phil. Thanks for the bug report. All bug reports are required to use our
[bug report template][2]. See also our [contributing guide][1].

[1]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
