### ISSUE TITLE
What about storing whodunnit UserID as integer instead of string?

### ISSUE THREAD

**Issue by kirylpl** [paper-trail-gem/paper_trail#1178]
Hey.
Is it really good idea to store whodunnit user ID as a string?
https://github.com/paper-trail-gem/paper_trail/blob/master/lib/generators/paper_trail/install/templates/create_versions.rb.erb#L16

It can cause problems when we use it as a foreign_key, f.e. 

```
module PaperTrail
  class Version < ::ActiveRecord::Base
    belongs_to :user, foreign_key: :whodunnit
  end
end
```

I can prepare PR if it's suitable idea.

Thanks.

**Comment by kirylpl** [comment]
I suppose it's actual story and there was gem for that even https://github.com/ankit1910/paper_trail-globalid

**Comment by maxmercy** [comment]
You can adapt the whodunnit format as you need in the migration by changing the type of the column.
For some user (as me) it is not good to have it as a integer as we are using uuid type of id.

**Comment by jaredbeck** [comment]
Hi Kiryl, thanks for the suggestion. This has been discussed extensively over the last decade. Please search our issues for "whodunnit" and you can read the relevant discussions.
