### ISSUE TITLE
Active Record 6 support

### ISSUE THREAD

**Issue by jockee** [paper-trail-gem/paper_trail#1179]
Rails 6.0.0 beta1 was just released and Active Record 6 with it.

**Comment by jaredbeck** [comment]
> Rails 6.0.0 beta1 was just released and Active Record 6 with it.

Pull requests welcome, thanks.

**Comment by bousquet** [comment]
@jaredbeck Why is this not an open issue?  Just tried to upgrade to latest Rails and running into the same problem.
