### ISSUE TITLE
PaperTrail is sometimes logging no action (empty object_changes)

### ISSUE THREAD

**Issue by rdudacz** [paper-trail-gem/paper_trail#1181]
I am facing a problem when PaperTrail logs also no action to the **versions** table - here's an example of that:
- id: 12050
- itemType: Car
- item_id: 4419
- event: update
- whodunnit: 299
- object: ---
id: 
name:
surname:
color:
created_at: 
updated_at: 
- created_at: 2019-01-18 15:26:14.606225
- object_changes: --- {}

The point is - no user has updated this model, yet I can see this log in the **versions** table. The field **object** states all the attribute in the **Car** model, but with no values; and then the **object_changes** doesn't contain anything but `--- {}`.

Also, when I look at the `whodunnit` user - this user hasn't done this change, it looks like the user_id  is thrown here randomly - I suspect it might be caused by some Sidekiq job?

However, how do I get rid of these empty changes? Why are these records saved? How do I avoid saving them?

Thank you

**Comment by jaredbeck** [comment]
Thanks for the bug report. All bug reports are required to use our
[bug report template][2]. See also our [contributing guide][1].

[1]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
