### ISSUE TITLE
Add `original_version` method to more easily obtain the original version.

### ISSUE THREAD

**Issue by joshuapinter** [paper-trail-gem/paper_trail#1204]
- [x] I am committed to building this feature myself
- [x] I will respond to feedback, and build this feature, in a reasonable amount
  of time

**Is your feature suggestion related to a problem? Please describe.**

Getting the original version of an item is way too difficult. It stems from the fact that calling `reify` on the first `version` returns `nil` and not the original object. That's fine. But it means that you need to do some fancy footwork to get the original version of an object and also handle when an object doesn't have any changes (i.e. only a single `create` version).

You can see the issue in these two spots: 

- https://stackoverflow.com/questions/45353464/how-to-get-original-attribute-for-a-model-with-paper-trail/56258720#56258720

- https://github.com/paper-trail-gem/paper_trail/issues/475

**Describe the solution you'd like to build**

I want to add an `original_version` method to the `has_paper_trail` concern that will return the original version of an object, regardless of how many changes the object has.

So instead of writing something like this `versions.second&.reify || self` you can just write `original_version`.

**Describe alternatives you've considered**

`versions.second&.reify || self`

### Commit on Our Fork.

We're using `3.0-stable` branch so I forked that and [committed](https://github.com/joshuapinter/paper_trail/commit/b30f006de6b50c9db8af7e22926c9e246b2c18e6) our desired change there. No tests but we can certainly write them if you want this merged into master.

**Comment by jaredbeck** [comment]
Hi Joshua, thanks for the contribution.

> I want to add an original_version method to the has_paper_trail concern that will return the original version of an object, regardless of how many changes the object has.

Sounds like a useful method.

> I want to add an [the new] method to the has_paper_trail concern ..

In PT 6, to avoid AR model namespace pollution, we moved almost everything from `has_paper_trail.rb` to `lib/paper_trail/record_trail.rb`. So, I'd suggest that this new method go in `record_trail.rb` also.

> .. add an original_version method ..

The name is in keeping with other, similar methods: `previous_version` and `next_version`. (Which are, themselves, not a match for `source_version`, the former returning records while the later returns a `Version`) There may also be some slight confusion with the existing `originator` method (a name I've always thought too generic) We could call the new method `reify_original_version` to clarify that it returns a record rather than a version. Any other suggestions?

> No tests but we can certainly write them ..

Thanks, tests are required for all new features.

> .. if you want this merged into master.

Did you want it merged into a different branch in addition to master? We don't usually do backports, except for important stuff like security patches.

**Comment by joshuapinter** [comment]
Thanks for the quick reply, @jaredbeck!

> In PT 6, to avoid AR model namespace pollution, we moved almost everything from has_paper_trail.rb to lib/paper_trail/record_trail.rb. So, I'd suggest that this new method go in record_trail.rb also.

Makes sense, thanks. We're on the old version so once we update we'll make this change to `record_trail.rb` instead.

> The name is in keeping with other, similar methods: previous_version and next_version. (Which are, themselves, not a match for source_version, the former returning records while the later returns a Version) There may also be some slight confusion with the existing originator method (a name I've always thought too generic) We could call the new method reify_original_version to clarify that it returns a record rather than a version. Any other suggestions?

Naming is always tough. :) I definitely see your point about the method not returning a `Version` instance. I didn't consider that at first. I think `reify_original_version` is on the right track and would certainly indicate the object is returned. Is `reify_original` not explicit enough? Let me know what you think.

> Did you want it merged into a different branch in addition to master? We don't usually do backports, except for important stuff like security patches.

`master` is good. We'll update our app to use your latest version before submitting this PR so we can use it in production and verify all is working well.

Thanks!

**Comment by jaredbeck** [comment]
> Naming is always tough. :) .. `reify_original` ..?

`reify_original` sounds good to me. Let's go with that for now.

> We'll update our app to [the] latest version ..

I strongly recommend updating one major version at a time. There have been many breaking changes over the years, all documented in the changelog, and some with runtime deprecation warnings. If you upgrade one major at a time, you can benefit from said warnings.

**Comment by joshuapinter** [comment]
>  I strongly recommend updating one major version at a time. There have been many breaking changes over the years, all documented in the changelog, and some with runtime deprecation warnings. If you upgrade one major at a time, you can benefit from said warnings.

Couldn't agree more. As a policy, everything we do at [CNTRAL](https://www.cntr.al/) is statically versioned. So no `>=` or `^` in `Gemfile` or `package.json`. And then when we upgrade we do it one version at a time and read through all of the Release notes and/or `CHANGELOG` entries.

Thanks again, will keep you posted! :+1:

**Comment by jaredbeck** [comment]
> We'll update our app to use your latest version before submitting this PR .. will keep you posted!

Closing in anticipation of PR. Thanks, Joshua.

**Comment by joshuapinter** [comment]
Oh noe. Sorry for the tardiness. Was just revisiting this.

**Comment by jaredbeck** [comment]
> Oh noe. Sorry for the tardiness. Was just revisiting this.

No worries at all. Take your time. I just figured the discussion was complete, so I could mark it off the list.

**Comment by cameronbourgeois** [comment]
+1 I think this feature would be handy.

**Comment by DanielStevenLewis** [comment]
Did something like this feature get added to PaperTrail? If not should the issue be re-opened?

**Comment by joshuapinter** [comment]
@DanielStevenLewis Not as far as I'm aware. We're still using it in our fork but haven't found the time to submit a PR back upstream.

**Comment by duhaime** [comment]
@joshuapinter @jaredbeck can this be reopened? It seems super odd one can't reify the first version of an object, this should be possible

**Comment by joshuapinter** [comment]
Just following up on this as I finally got around to making the minor mods and stubbing out a [PR](https://github.com/paper-trail-gem/paper_trail/pull/1504) for it. 

I'll wait to ensure there is still interest in adding this before adding tests. FYI, we're still using this in production and it's been working well for us.

Thanks.

**Comment by joshuapinter** [comment]
FYI, I've finalized the PR with specs and a CHANGELOG so it should be good to go. Just needs to get reviewed and merged into `master`.
