### ISSUE TITLE
Usage question: using paper trail for 'future' versions

### ISSUE THREAD

**Issue by hidde-jan** [paper-trail-gem/paper_trail#1205]
Currently, you can (ab)use paper trail to 'schedule' a draft changeset to a certain object by doing something along the following lines

```ruby
class Widget < ActiveRecord::Base
  has_paper_trail
end

widget = Widget.create title: "MyWidget"  # stores version

# ... later ...

widget.title = "MyBetterWidget"

widget.transaction do
  widget.save
  if (prev = widget.paper_trail.previous_version)
    prev.save  # make sure to suppress new version
  else
     widget.destroy  # make sure to suppress new version
  end
end
```

One could also use something like

```ruby
widget.paper_trail.record_update force: true,  # ???
  in_after_callback: false,  # ???
  is_touch: false  # ???
```
without actually persisting the changes on the widget. From the version that are being created, this doesn't seem to work really well with how versions are created, i.e. new create event after recreating a deleted object and creating a new update event after reifying and saving a previous version. Thus, this might be a bad idea.

A better option might be to create a second version class, like PotentialVersion in a separate table and somehow reify and save that version. The only problem is that I can't really see how that would work.

Any ideas or comments as to why this is a bad idea would be greatly appreciated.

**Comment by hidde-jan** [comment]
My bad. I've found a related question on SO at https://stackoverflow.com/questions/38685592/building-an-active-record-scope-of-editor-approved-versions-of-user-generated

**Comment by jaredbeck** [comment]
Hi Hidde-Jan. Congratulations, you are the first person to speak to @paper-trail-bot :grin:

Glad you found something useful on SO.

**Comment by hidde-jan** [comment]
Hi Jared,

Thanks 🤖 

For future reference, I found https://github.com/copasetickid/draftsman, which is heavily inspired by paper trail.

**Comment by schmijos** [comment]
I'd still be interested into how you could idiomatically solve this problem with _PaperTrail_. Shouldn't you simply be able to navigate into the future with `next`? Or is this too naïve?

**Comment by jaredbeck** [comment]
> Due to limited volunteer time, please ask usage questions on [StackOverflow][2].
