### ISSUE TITLE
pass value of variable from view

### ISSUE THREAD

**Issue by ZAJDAN** [paper-trail-gem/paper_trail#1210]
In version I created new column 'localip' .
In view I have hidden field where I put value via JS:
` <%= f.hidden_field :localIP, :value => params[:localIP] %>`

If I understand correctly  the paper_trail is called as first, so I put in my controller:
```
  prepend_before_action :set_localip, only: :update   

  def info_for_paper_trail
     { 
       :ip => request.remote_ip, 
       :agent => request.user_agent,
       :localip => @localip
      }
  end

private
    def set_localip
       @localip = params[:localIP] 
    end
```
but during update :localip is not passed:
**PaperTrail::Version Create (0.3ms)  INSERT INTO "versions" ("item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "ip", "agent") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)**

do anybody know how to pass such value?

**Comment by jaredbeck** [comment]
I responded to [this question on StackOverflow](https://stackoverflow.com/questions/56564357/pass-variable-to-method-info-for-paper-trail). Let's keep the conversation there until a bug has been confirmed, thanks.
