### ISSUE TITLE
Documentation issue for undeleting a model

### ISSUE THREAD

**Issue by James1345** [paper-trail-gem/paper_trail#1211]
Documentation gives an example of undeleting a model as 

```ruby
widget = Widget.find(42)
widget.destroy
# Time passes....
versions = widget.versions    # versions ordered by versions.created_at, ascending
widget = versions.last.reify  # the widget as it was before destruction
widget.save           
```

However, if the widget with id 42 has been deleted in a separate session (e.g. a web request) there is no result to find - the code given will not work. It is easy enough to work around with `Widget.new(id:42).versions.last.reify.save` - this should be mentioned

**Comment by jaredbeck** [comment]
> It is easy enough to work around with Widget.new(id:42).versions.last.reify.save - this should be mentioned

Makes sense. Please create a pull request, thanks!

**Comment by estani** [comment]
Not so sure why is so hard to get a pull request into the project, but here's my try at it.
I came to the same conclusion as here, but lost some time while at it... this would have helped me. So I hope this helps others.

thanks @James1345
