### ISSUE TITLE
Enabled logic doesn't seems to cover whitelisting cases.

### ISSUE THREAD

**Issue by ce07c3** [paper-trail-gem/paper_trail#1227]
Actual behavior:

- `PaperTrail.config.enabled = false` in an initialiser is not respected and eventually overridden by the PaperTrail Rails engine
- `PaperTrail.request.enabled = true` cannot be used to whitelist specific calls, but disallow all other use cases:

```rb
# RecordTrail class
def enabled?
  PaperTrail.enabled? &&
    PaperTrail.request.enabled? &&
    PaperTrail.request.enabled_for_model?(@record.class)
end
```

Will always evaluate to `false` if `PaperTrail.enabled` evaluates to `false`. 

Expected behavior:

- PaperTrail can be turned off globally, but still be used per request

Would like feedback if this makes sense, I can draft a PR.

**Comment by jaredbeck** [comment]
Hi Carl. All issues are required to use our [issue template][2]. See also our [contributing guide][1]. Please review the issue template, open a new issue, and I'll do what I can to help!

[1]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ce07c3** [comment]
The issue is clear as it is. If you don’t need contributions - ok!
