### ISSUE TITLE
Contribution guidelines ethics

### ISSUE THREAD

**Issue by vldcmp** [paper-trail-gem/paper_trail#1234]
Hello,

Judging on the closed issues, I'm pretty sure I am not the only one with this curiosity.

What exactly is the logic behind not being able to **just** report bugs? Nobody is demanding that it should be fixed as soon as possible, not even mentioning it should be fixed in the first place.

It's just perplexing that you can not do the most basic thing to help a project grow. Having hardly any opened issues now makes sense.

Most definitely there have been others who wanted to contribute, but backed off when finding out about this policy.

**Comment by ce07c3** [comment]
> Hello,
> 
> Judging on the closed issues, I'm pretty sure I am not the only one with this curiosity.
> 
> What exactly is the logic behind not being able to **just** report bugs? Nobody is demanding that it should be fixed as soon as possible, not even mentioning it should be fixed in the first place.
> 
> It's just perplexing that you can not do the most basic thing to help a project grow. Having hardly any opened issues now makes sense.
> 
> Most definitely there have been others who wanted to contribute, but backed off when finding out about this policy.

Agree. I suppose it's to make the gem look well-maintained?
