### ISSUE TITLE
object_changes is stored for destroy event

### ISSUE THREAD

**Issue by bli** [paper-trail-gem/paper_trail#1236]
The current readme page says:

> The object_changes are only stored for creation and updates, not when an object is destroyed.

But this seems outdated. For some reason, paper_trail has been changed to store object_changes on destroy event as well.

**Comment by tlynam** [comment]
Thank you for catching this, would you mind opening a PR to fix this?  It seems like we can remove this line.

**Comment by FanaHOVA** [comment]
See #1239

**Comment by CodeMonkeySteve** [comment]
Is there a way to prevent `object_changes` from being stored on destroy events?  It seems like a waste of disk, at least for my use case.
