### ISSUE TITLE
Feature: S3 backend for object and object_changes to reduce database storage

### ISSUE THREAD

**Issue by itghlu** [paper-trail-gem/paper_trail#1246]
### Problem

Our application use case requires indefinite storage of all `versions` data with inclusion of the `object` and `object_changes` columns. At present, there are over ~2.5 billion records using multiple terabytes of database storage, and this number is very fast growing. The data for `object` and `object_changes` represent half of the table size.

The growing storage cost is quite expensive so we need to take steps to address this.

### Proposed Solution

Allow the `object` and `object_changes` data to be stored in a separate, configurable backend. We have looked into using S3 which provides storage at 1/10 the cost of RDS where our application database is hosted.

The feature set that would be implemented:
* Allow reading and writing of `object` and `object_changes`.
* Allow `reify` calls using the `object` data.
* Allow `changeset` calls using the `object_changes` data.

We plan to store both `object` and `object_changes` in a single S3 object to minimize requests, and interact with S3 using simple PutObject and GetObject calls.

We are aware that PaperTrail performs SQL queries against these columns in `where_object` and `where_object_changes`. These features are not used in our application so we do not have plans to support them.

### Alternatives

Our goal is to reduce database storage for cost reasons, and as the `object` and `object_changes` represent a significant portion of this, removing this data would need to be a requirement in the long term.

Alternatives are to monkey patch or fork PaperTrail for our own purposes, or implement an in-house alternative to PaperTrail. These alternatives are still being considered, but having PaperTrail support provides an easier avenue for future gem upgrades.

**Comment by tlynam** [comment]
I'm unable to speak for S3 support.  For saving space, if you keep all the records, could you skip saving the `object` attribute?  Do you need `updated_at` and `created_at`?  There have been discussions around these and removing `object` and timestamps would save a lot of space.

https://github.com/paper-trail-gem/paper_trail/issues/1046
https://github.com/paper-trail-gem/paper_trail/issues/1099
https://github.com/paper-trail-gem/paper_trail/issues/1129

**Comment by itghlu** [comment]
`reify` is an important part of our application behavior (needed for both update and destroy operations) so dropping `object` would not be an option us. Removing the timestamps is an idea we could look into though.

However, given that the object columns are still the largest user of space, this would still be the higher priority target for us to address.

**Comment by jacobthemyth** [comment]
I work on application that also needs this feature. We also don’t use `where_object` and `where_object_changes`, though this could be implemented via Athena if necessary. I’m happy to collaborate on this @itghlu if the maintainers would accept this feature.

**Comment by gurgelrenan** [comment]
In my opinion is a good feature. In our application, `versions` is the largest table and like @itghlu sad RDS is much more expensive than S3 or something like that. Maybe we can figure out the best approach for this feature with @jacobthemyth helps.

**Comment by jaredbeck** [comment]
Rather than having S3 support in paper_trail core, I'd prefer it be a plugin (separate gem), for a few reasons:

- I don't anticipate these features being used by most people
- I don't want PT core to depend on AWS libraries, like `fog` or `aws-sdk`
- It's a big new set of features and I don't want to support it

Historically, PT has been extensible enough to support some powerful plugins (see [readme sections 8-9](https://github.com/paper-trail-gem/paper_trail#8-papertrail-plugins)), so an S3 plugin should be possible. 

In keeping with rubygems naming conventions, the gem name should contain a hyphen, e.g. `paper_trail-s3`.

If, in writing your new gem, you find that PT is not extensible enough, or you have questions about what to hook into, I'll be happy to help with that.

**Comment by itghlu** [comment]
We started moving on a couple months ago and went the route of implementing an internal PaperTrail extension, using similar concepts to PaperTrail plugins.

A large reason we were hoping to have this feature accepted into the core project was to ensure future support, and maintaining a new publicly available plugin project is not something we could commit time to at the moment.

Thanks for your feedback and others that have shown interest.

**Comment by chernesk** [comment]
Is there any chance of sharing this internal implementation? I have the exact same need and would love to use it. Thanks!

**Comment by gurgelrenan** [comment]
@chernesk take a look at this comment from @jaredbeck. 

> Rather than having S3 support in paper_trail core, I'd prefer it be a plugin (separate gem), for a few reasons:
> 
> * I don't anticipate these features being used by most people
> * I don't want PT core to depend on AWS libraries, like `fog` or `aws-sdk`
> * It's a big new set of features and I don't want to support it
> 
> Historically, PT has been extensible enough to support some powerful plugins (see [readme sections 8-9](https://github.com/paper-trail-gem/paper_trail#8-papertrail-plugins)), so an S3 plugin should be possible.
> 
> In keeping with rubygems naming conventions, the gem name should contain a hyphen, e.g. `paper_trail-s3`.
> 
> If, in writing your new gem, you find that PT is not extensible enough, or you have questions about what to hook into, I'll be happy to help with that.

**Comment by chernesk** [comment]
@gurgelrenan yes, I had read that. I was hoping that @itghlu could share their internal extension so that I didn't have to re-create the plugin again.

**Comment by tilo** [comment]
@jaredbeck I understand that it is a big ask, but would you be able to define an internal API to interact with the DB, and isolate the mysql calls to a plugin as you described?

This would make it much easier for other contributors to adapt PT to other storage engines
