### ISSUE TITLE
Introduce navigating through versions id

### ISSUE THREAD

**Issue by kushthedude** [paper-trail-gem/paper_trail#1248]
Thank you for your contribution!

Due to limited volunteers, issues that do not follow this template will be
closed without comment.

**Is your feature suggestion related to a problem? Please describe.**

No, I would love to have a feature for navigating through the changes using the version_id attribute which is present in paper_trail schema.

**Describe the solution you'd like to build**

Have a method to navigate through the changes in the model using the version_id.

**Describe alternatives you've considered**

Not much, but I think this should be given to users as I couldn't find any way to go through my changes other than `last` and `next`.

**Comment by kushthedude** [comment]
cc: @tlynam

**Comment by tlynam** [comment]
Hi @kushthedude, thank you for submitting this!  I'm trying to wrap my head around your idea.  Do you have some pseudo code that could help me understand it more?  When talking about going through changes using `last` and `next`, what is `changes` in this context?  Is it `object_changes`?

**Comment by kushthedude** [comment]
Hey @tlynam 
Something like having a feature to navigate through the versions using versions id like what audited gem provides, https://github.com/collectiveidea/audited#usage.
```rb
user.revisions
user.revision(1)
user.revision_at(Date.parse("2016-01-01"))
```

As I see paper trail already indexes each version with version_id but we only have two methods to navigate through the version `next & last`, it would be better if I could see the version with the version id.

**Comment by gurgelrenan** [comment]
Hi @kushthedude.

The `user.revision (1)` method in the `Audited` gem was not found by the version ID, but by the array index. Is this behavior you are suggesting?

**Comment by kushthedude** [comment]
Yes

**Comment by jaredbeck** [comment]
How about `user.versions.to_a[index]`?

**Comment by kushthedude** [comment]
This works but we found out about this hack earlier with @gurgelrenan 

> How about `user.versions.to_a[index]`?
> 
> Or, `user.versions.offset(index).limit(1)`.
> 
> (The `versions` association orders by `created_at` by default)
