### ISSUE TITLE
Feature: save changes between versions, not just from last save event

### ISSUE THREAD

**Issue by dertel** [paper-trail-gem/paper_trail#1251]
**Is your feature suggestion related to a problem? Please describe.**
In web apps that don't have a save button, there usually isn't a save button but rather the frontend automatically saves user input as they enter it. This results in several update events even if the user is just going in and changing a few fields in a record. The problem here is that many paper_trail version records are created, each one showing a small part of the overall changes made by the user during that short period of editing. This results in less meaningful change histories for users.

**Describe alternatives you've considered**
We hoped to use `my_model.paper_trail.save_with_version` to manually track the changes between the last created version. We would disable all version creation on update  via something like `has_paper_trail if:     Proc.new { |t| false }` and insead schedule a worker to trigger `save_with_version` after x minutes of inactivity on that record.

However we found that `save_with_version` only tracks the changes that happen in the last update event, not since the last *version* was created.

**Describe the solution you'd like to build**
Adding an option where each time a version is created, paper_trail diffs the changes from the last version rather than just that most recent save event.

**Comment by jaredbeck** [comment]
> In web apps that don't have a save button .. This results in several update events .. [thus] .. less meaningful change histories ..

Hi! I like how you've described the problem. Makes sense.

> However we found that save_with_version only tracks the changes that happen in the last update event, not since the last version was created.

Probably because PaperTrail uses `ActiveModel::Dirty` to track changes.

> Adding an option where each time a version is created, paper_trail diffs the changes from the last version rather than just that most recent save event.

Something like `save_with_version(ignore_dirty_and_diff_from_last_version: true)`? 😁  Makes sense. I'd be interested in reviewing a PR. Please see CONTRIBUTING.md for development instructions.

Alternatively, one could consider solving this problem on the frontend. When viewing the history of changes, the UI could collapse changes that occur around the same time.

**Comment by dertel** [comment]
Thanks @jaredbeck

For anyone curious, I created this after_commit task to delete versions that were recently saved within the timeframe of the variable `resolution`:

```
    after_commit {
      # only keep one version for every hour, unless it is by a different user
      # if there's a lot of versions for this record, switch to every 24 hours
      versions_reverse = self.versions.reverse
      resolution = 1.hour
  
      if versions_reverse.length > 20
        resolution = 24.hours
      end
  
      versions_reverse.each_with_index do |version, i|
        prev_version = versions_reverse[i-1]

        if (
          i > 0 && 
          prev_version && 
          (prev_version.created_at - version.created_at) < resolution &&
          version.object.try(:[], "user_id") == prev_version.object.try(:[], "user_id")
        )
          version.destroy
        end
      end
    }
```

**Comment by dertel** [comment]
Also, @jaredbeck would it be helpful if I refined this code and added a config option for paper_trail in a PR (following the contribution guidelines)? like 

```
    has_paper_trail(
      resolution: 1.hour
    )
```

or a proc for more complex logic

```
    has_paper_trail(
      resolution: proc { |obj| obj.versions.length > 40 ? 1.day : 1.hour } 
    )
```

If this feature is too niche of a use case or not a good fit then no worries.

**Comment by jaredbeck** [comment]
> .. would it be helpful if I refined this code and added a config option for paper_trail ..

I appreciate the idea, but it feels a bit out of scope for PT. Also, there are other solutions, like `debounce`ing your frontend `onChange` handlers.

I'd love to have you share what you've learned by adding it to the readme. Either Section 2, "2. Limiting What is Versioned", or creating a new section like "11. Application Patterns -> 11.a. Auto-saving Frontend" would be good places.

Also, if you want to write a PT plugin, there are a handful of other [plugins](https://github.com/paper-trail-gem/paper_trail/#8-papertrail-plugins) that you can copy the structure from. If enough people adopt the plugin, that can inform our decision about adding a feature to PT core.
