### ISSUE TITLE
`touch` on `belongs_to` association also updating paperclip versions

### ISSUE THREAD

**Issue by dhurba87** [paper-trail-gem/paper_trail#1262]
- [x] This is not a usage question, this is a bug report
- [x] This bug can be reproduced with the script I provide below
- [x] This bug can be reproduced in the latest release of the `paper_trail` gem

Bug reports must use the following template:

```ruby
# frozen_string_literal: true

# Use this template to report PaperTrail bugs.
# Please include only the minimum code necessary to reproduce your issue.
require "bundler/inline"

# STEP ONE: What versions are you using?
gemfile(true) do
  ruby "2.7.1"
  source "https://rubygems.org"
  gem "activerecord", "5.2.0"
  gem "minitest", "5.11.3"
  gem "paper_trail", "9.2.0", require: false
  gem "sqlite3", "1.3.13"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Please use sqlite for your bug reports, if possible.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = nil
ActiveRecord::Schema.define do
  # STEP TWO: Define your tables here.
  create_table :users, force: true do |t|
    t.text :first_name
    t.text :last_name
    t.timestamps null: false
  end

  create_table :articles, force: true do |t|
    t.string :title
    t.references :user, null: false, foreign_key: true
    t.timestamp null: false
  end

  create_table :versions do |t|
    t.string :item_type, null: false
    t.integer :item_id, null: false
    t.string :event, null: false
    t.string :whodunnit
    t.text :object, limit: 1_073_741_823
    t.text :object_changes, limit: 1_073_741_823
    t.datetime :created_at
  end
  add_index :versions, %i[item_type item_id]
end
ActiveRecord::Base.logger = Logger.new(STDOUT)
require "paper_trail"

# STEP FOUR: Define your AR models here.
class User < ActiveRecord::Base
  has_paper_trail only: [:first_name]
  has_many :articles
end

class Article < ActiveRecord::Base
  belongs_to :user, touch: true
end

# STEP FIVE: Please write a test that demonstrates your issue.
class BugTest < ActiveSupport::TestCase
  def test_1
    user = User.create first_name: 'Jane'
    assert_equal(user.versions.count, 1)

    user.articles.create! title: 'article title'
    assert_equal(user.versions.count, 1)
  end
end

# STEP SIX: Run this script using `ruby my_bug_report.rb`

```
Test output (`ruby my_bug_report.rb`):
```
Finished in 0.039558s, 25.2793 runs/s, 50.5587 assertions/s.

  1) Failure:
BugTest#test_1 [my_bug_report.rb:69]:
Expected: 2
  Actual: 1

1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by rabinpoudyal** [comment]
Faced the same issue.

**Comment by tlynam** [comment]
Hi @jaredbeck, I'm trying to confirm the expected behavior when touching an object that has `only` defined.  Do we create a version with attributes from `only`?  So in this case we shouldn't create a version because `only` doesn't contain `updated_at`?

**Comment by jaredbeck** [comment]
> [what is] the expected behavior when touching an object that has `only` defined?

I can't recall ever discussing this exact situation, ie. an association using the `touch:` option. We don't have any tests that cover such an association.

The documentation for `only:` says: 

> Only changes to the [specified attributes] will create a version record.

I'm inclined to let that guide us.

> So in this case we shouldn't create a version because `only` doesn't contain updated_at?

Yeah, that's how I interpret the intention of `only`.

Thanks for the nice bug report, @dhurba87.

**Comment by benben** [comment]
I can confirm this. Especially annoying since rails' new ActiveStorage does this under the hood with `has_one_attached`.

**Comment by benben** [comment]
Also nothing is triggered in this situation: `if`, `unless`, `skip`, `ignore` is all not working. It seems like `has_paper_trail` is not doing anything in that case beside writing another version ;)
