### ISSUE TITLE
String with numeric value and underline as final char is raising error

### ISSUE THREAD

**Issue by aneziocampos** [paper-trail-gem/paper_trail#1267]
When you try to save in your model any value like: '30015_', '10_', '45_' and so on, it returns the following error:
`ArgumentError: invalid value for Integer()`

I've tested multiple models, that error happens on any field only on the models with `has_paper_trail`. When I remove papertrail it saves normally.

I'm using:
ruby 2.7.1
rails 6.0.3.4
papertrail: 11.0.0
pg: 1.2.3

Test:
```
# frozen_string_literal: true

# Please include only the minimum code necessary to reproduce your issue.
require "bundler/inline"

# STEP ONE: What versions are you using?
gemfile(true) do
  ruby "2.7.1"
  source "https://rubygems.org"
  gem "activerecord", "6.0.3.4"
  gem "minitest", "5.14.2"
  gem "paper_trail", "11.0.0", require: false
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = nil
ActiveRecord::Schema.define do

  create_table :users, force: true do |t|
    t.text :first_name, null: false
    t.timestamps null: false
  end
  create_table :companies, force: true do |t|
    t.text :name, null: false
    t.timestamps null: false
  end

  create_table :versions do |t|
    t.string :item_type, null: false
    t.integer :item_id, null: false
    t.string :event, null: false
    t.string :whodunnit
    t.text :object, limit: 1_073_741_823
    t.text :object_changes, limit: 1_073_741_823
    t.datetime :created_at
  end
  add_index :versions, %i[item_type item_id]
end
ActiveRecord::Base.logger = Logger.new(STDOUT)
require "paper_trail"

class User < ActiveRecord::Base
  has_paper_trail
end

class Company < ActiveRecord::Base
  # no papertrail
end

class BugTest < ActiveSupport::TestCase
  def test_model_without_papertrail
    c = Company.new
    c.name = '30_'
    c.save

    assert_equal(c.name, '30_')
  end

  def test_model_with_papertrail
    u = User.new
    u.first_name = '30_'
    u.save

    assert_equal(u.first_name, '30_')
  end
end

```

**Comment by tlynam** [comment]
Hi @aneziocampos, thank you so much for submitting such a detailed bug report!  It looks like this is a bug that has been fixed in psych version 3.2.  The fix PR also provides a monkey patch.
https://github.com/ruby/psych/issues/442
https://github.com/ruby/psych/pull/445

**Comment by aneziocampos** [comment]
Just in case anyone else is looking for a solution I've tested two ways to solve this issue and they both worked:

1 - Add [this patch](https://github.com/ruby/psych/pull/445#issue-399517363) to your project
2 - Add the gem `gem 'psych', '3.2.0'` to your Gemfile

Thanks @tlynam for the help.

**Comment by chetankothari** [comment]
> Just in case anyone else is looking for a solution I've tested two ways to solve this issue and they both worked:
> 
> 1 - Add [this patch](https://github.com/ruby/psych/pull/445#issue-399517363) to your project 2 - Add the gem `gem 'psych', '3.2.0'` to your Gemfile
> 
> Thanks @tlynam for the help.

Thank you @aneziocampos and @tlynam. Using `gem 'psych', '3.2.0'` worked.
