### ISSUE TITLE
PaperTrail 11.0.0 is not compatible with ActiveRecord 6.1.0

### ISSUE THREAD

**Issue by sedubois** [paper-trail-gem/paper_trail#1272]
**Is your feature suggestion related to a problem? Please describe.**

PaperTrail is currently untested against Rails 6.1.0 and emits a warning on startup:
```
      PaperTrail 11.0.0 is not compatible with ActiveRecord 6.1.0. We allow PT
      contributors to install incompatible versions of ActiveRecord, and this
      warning can be silenced with an environment variable, but this is a bad
      idea for normal use. Please install a compatible version of ActiveRecord
      instead (>= 5.2, < 6.1). Please see the discussion in paper_trail/compatibility.rb
      for details.
```

**Describe the solution you'd like to build**

- add ActiveRecord 6.1.0 to .travis.yml
- fix any observed incompatibilities
- update `ACTIVERECORD_LT` in `lib/paper_trail/compatibility.rb`

**Describe alternatives you've considered**

Ignore the warning. No regressions observed thus far.

**Comment by jaredbeck** [comment]
```
Describe the solution you'd like to build

    add ActiveRecord 6.1.0 to .travis.yml
    fix any observed incompatibilities
    update ACTIVERECORD_LT in lib/paper_trail/compatibility.rb
```

Perfect! You got it, go for it! 👍

**Comment by pedrofurtado** [comment]
🎉

**Comment by jaredbeck** [comment]
Closing via #1275
