### ISSUE TITLE
PaperTrail.config.enabled is not working

### ISSUE THREAD

**Issue by noma4i** [paper-trail-gem/paper_trail#1283]
As per https://github.com/paper-trail-gem/paper_trail#1e1-global
setup initializer:

config/initializers/paper_trail.rb
```ruby
PaperTrail.config.enabled = false
```

Expected: Versions not to be created
Actual: Versions are created

rails console: 
![image](https://user-images.githubusercontent.com/210667/103453805-c5129e00-4d31-11eb-9e46-c305b2b51220.png)

**Comment by leshik** [comment]
This issue is pretty nasty...
