### ISSUE TITLE
Why YAML is the default data type on paper_trail?

### ISSUE THREAD

**Issue by unkn0wn-developer** [paper-trail-gem/paper_trail#1290]
**Is your feature suggestion related to a problem? Please describe.**

Why YAML is the default data type on paper_trail? 
Every answer I find is regarding the fact that YAML is easy to read and that's it.
But who cares? the data is on the database. It's not like a config file or anything.
I just wonder if I'm missing out on something. 

**Describe the solution you'd like to build**

A clear and concise description of what you want to build.

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've
considered.

**Comment by tlynam** [comment]
It looks like this has been discussed before https://github.com/paper-trail-gem/paper_trail/issues/555
