### ISSUE TITLE
Migration Rails 4.1 to 4.2 - Error event required

### ISSUE THREAD

**Issue by mariohmol** [paper-trail-gem/paper_trail#1296]
Hi there,

I have an app that we are migrating from 4.1 to 4.2 , this was working before and then we updated to the latest papertrail version.

But now when I try to save a module it gives me {event: [required]}.

I have something like that:
```rb
has_paper_trail meta: { perfil_id: Proc.new { |sociedade| sociedade.id }, perfil_tipo: Proc.new { |sociedade| sociedade.class.name } }
```

Any ideas?

thanks

**Comment by tlynam** [comment]
Hi @mariohmol, thank you for opening this!  Would it be possible to use our bug template?  It'll help us reproduce the issue.

https://github.com/paper-trail-gem/paper_trail/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

**Comment by mariohmol** [comment]
Hi, we ended up removing the gem from the project!

thanks

**Comment by mariohmol** [comment]
An update from whom get's the same issue: after removing the `meta: ...` it worked..
we are trying to put the gen back but we are running over other issues... this time it doesnt save the model and does not return any error msg..

version: paper_trail (10.3.1)
