### ISSUE TITLE
uninitialized constant PaperTrail::Rails

### ISSUE THREAD

**Issue by sedubois** [paper-trail-gem/paper_trail#1300]
[Following the Wiki documentation](https://github.com/paper-trail-gem/paper_trail/wiki/Setting-whodunnit-in-the-rails-console#setting-automatically-based-on-current-os-user) I have `PaperTrail::Rails::Engine.eager_load!` in my initializer. However this breaks when upgrading to PT 12.0.0.

- [x] This is not a usage question, this is a bug report
- [x] This bug can be reproduced with the script I provide below
- [x] This bug can be reproduced in the latest release of the `paper_trail` gem

```ruby
# frozen_string_literal: true

# Use this template to report PaperTrail bugs.
# Please include only the minimum code necessary to reproduce your issue.
require "bundler/inline"

# STEP ONE: What versions are you using?
gemfile(true) do
  ruby "2.5.1"
  source "https://rubygems.org"
  gem "activerecord", "5.2.0"
  gem "minitest", "5.11.3"
  gem "paper_trail", "9.2.0", require: false
  gem "sqlite3", "1.3.13"
end

require "active_record"
require "minitest/autorun"
require "logger"

PaperTrail::Rails::Engine.eager_load!

# Please use sqlite for your bug reports, if possible.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = nil
ActiveRecord::Schema.define do
  # STEP TWO: Define your tables here.
  create_table :users, force: true do |t|
    t.text :first_name, null: false
    t.timestamps null: false
  end

  create_table :versions do |t|
    t.string :item_type, null: false
    t.integer :item_id, null: false
    t.string :event, null: false
    t.string :whodunnit
    t.text :object, limit: 1_073_741_823
    t.text :object_changes, limit: 1_073_741_823
    t.datetime :created_at
  end
  add_index :versions, %i[item_type item_id]
end
ActiveRecord::Base.logger = Logger.new(STDOUT)
require "paper_trail"

# STEP FOUR: Define your AR models here.
class User < ActiveRecord::Base
  has_paper_trail
end

# STEP FIVE: Please write a test that demonstrates your issue.
class BugTest < ActiveSupport::TestCase
  def test_1
    
  end
end

# STEP SIX: Run this script using `ruby my_bug_report.rb`
```

**Comment by mensfeld** [comment]
@sedubois PT works for me after I removed the `PaperTrail::Rails::Engine.eager_load!` from the initializer.

**Comment by sedubois** [comment]
@mensfeld for me too. And printing `::PaperTrail.request.whodunnit` in a Rails task seems to work. 

So should the [Wiki](https://github.com/paper-trail-gem/paper_trail/wiki/Setting-whodunnit-in-the-rails-console#setting-automatically-based-on-current-os-user) be updated to this?

```diff
-# the following line is required for PaperTrail >= 4.0.0 with Rails
+# the following line is required for PaperTrail >= 4.0.0 and < 12.0.0 with Rails
PaperTrail::Rails::Engine.eager_load!
```

**Comment by mensfeld** [comment]
Probably but I do not know the internals too much.

**Comment by tlynam** [comment]
Thank you for opening this and finding a solution!  I agree, it looks like the Wiki should be updated.  The loading was changed in #1281.  Does this sound good to you @jaredbeck?

**Comment by jaredbeck** [comment]
As the changelog says, `PaperTrail::Rails::Engine` no longer exists. Please feel free to update the wiki accordingly.

> Following the Wiki documentation ..

When looking for _official_ documentation, please refer to the readme and the code comments. Speaking for myself, I've spent hundreds of hours working on the readme, but I don't make any effort to maintain the wiki.

**Comment by tlynam** [comment]
Sounds good!  I went ahead and updated the wiki document.
