### ISSUE TITLE
Feature: Ignore Attributes in Object Column That are Equal to Their Default Value

### ISSUE THREAD

**Issue by BenMorganIO** [paper-trail-gem/paper_trail#1306]
Thank you for your contribution!

Due to limited volunteers, issues that do not follow this template will be
closed without comment.

**Is your feature suggestion related to a problem? Please describe.**

We currently have ~2GB of version data for our orders. It's mainly because the table has many columns and it is frequently updated and changed through the ecommerce lifecycle.

**Describe the solution you'd like to build**

We're looking to thin the table down by removing attributes that are equal to the default value of the instance. We believe this will not impact `reify` and `where_object` since those values can be obtained from the model.

**Describe alternatives you've considered**

Drop the column but we need reify to work. We may end up monkey patching this ourselves without guidance.

**Comment by tlynam** [comment]
Hi @BenMorganIO, would it be possible to use `ignore`?  Or maybe `ignore` with a proc?  https://github.com/paper-trail-gem/paper_trail#ignore

**Comment by BenMorganIO** [comment]
I think I tried this. Ignore only works on object changes. We needed it to be skipped on object. The proc is a small bit of an issue because I want to built a list of procs, not a proc per column, work through each column, instantiate an empty instance per column, and keep it up to date. I also would want it as a default since we have six version tables.

We've actually coded this feature and it retains having reify work. I can move it over in a PR for you to look at. This is incredibly important for size reduction.

**Comment by tlynam** [comment]
Okay, interesting, did you look into skip as well?  https://github.com/paper-trail-gem/paper_trail#skip
Feel free to create a PR and we can look at it. You could also explain it without spending too much development effort as we can't guarantee it'll be merged.

**Comment by BenMorganIO** [comment]
Yeah, looked at skip. I couldn't create a proc that creates proc's for me. I wanted a feature that would do a single `model.new` instead of `columns.each { |_| model.new }` to ensure things remain performant. I also needed it to be a bit more meta so it could be applied to all models and I don't have to copy/paste code from one model to another.
