### ISSUE TITLE
Unable to load schema with limit option

### ISSUE THREAD

**Issue by ryanb** [paper-trail-gem/paper_trail#1307]
If I add the `limit` option to `has_paper_trail` it will cause commands such as `rails db:schema:load` to fail. This prevents setting up the app in a new environment or running the test suite since the schema isn't loaded. I assume this is because the limit option depends on the `versions` table which is not created until after the schema is loaded.

---

- [x] This is not a usage question, this is a bug report
- [x] This bug can be reproduced with the script I provide below
- [x] This bug can be reproduced in the latest release of the `paper_trail` gem

```ruby
# frozen_string_literal: true

# Use this template to report PaperTrail bugs.
# Please include only the minimum code necessary to reproduce your issue.
require "bundler/inline"

# STEP ONE: What versions are you using?
gemfile(true) do
  ruby "2.5.5"
  source "https://rubygems.org"
  gem "activerecord", "6.0.3.6"
  gem "minitest", "5.11.3"
  gem "paper_trail", "12.0.0", require: false
  gem "sqlite3", "1.4.2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Please use sqlite for your bug reports, if possible.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = nil
ActiveRecord::Schema.define do
  # STEP TWO: Define your tables here.
  create_table :users, force: true do |t|
    t.text :first_name, null: false
    t.timestamps null: false
  end

  # versions table created after AR model is defined
end
ActiveRecord::Base.logger = Logger.new(STDOUT)
require "paper_trail"

# STEP FOUR: Define your AR models here.
class User < ActiveRecord::Base
  # Removing limit option works
  has_paper_trail limit: 5
end

# Define versions table after model is loaded to simulate db:schema:load command
ActiveRecord::Schema.define do
  create_table :versions do |t|
    t.string :item_type, null: false
    t.integer :item_id, null: false
    t.string :item_subtype
    t.string :event, null: false
    t.string :whodunnit
    t.text :object, limit: 1_073_741_823
    t.text :object_changes, limit: 1_073_741_823
    t.datetime :created_at
  end
  add_index :versions, %i[item_type item_id]
end

# STEP FIVE: Please write a test that demonstrates your issue.
class BugTest < ActiveSupport::TestCase
  def test_1
    assert_difference(-> { PaperTrail::Version.count }, +1) {
      User.create(first_name: "Jane")
    }
  end
end

# STEP SIX: Run this script using `ruby my_bug_report.rb`
```

Notice removing the `limit` option causes the script to pass.

**Comment by jaredbeck** [comment]
Hi Ryan. Glad to see you're still writing ruby these days! Been working on any libraries, or just apps?

> .. the versions table .. is not created until after the schema is loaded.

I see that this is the case in your script, but this would be an unusual sequence of events in an app. Per the [installation instructions](https://github.com/paper-trail-gem/paper_trail#1b-installation), the versions table should be created before the app is started. I must be missing something.

> This prevents setting up the app in a new environment or running the test suite since the schema isn't loaded.

I'm able to install PT (12.0) in a new rails app (6.1) and run some basic version-related tests. Can you provide a series of steps, starting with `rails new`, that demonstrates the issue?

**Comment by ryanb** [comment]
> Hi Ryan. Glad to see you're still writing ruby these days! Been working on any libraries, or just apps?

Just apps at the moment. :)

> I see that this is the case in your script, but this would be an unusual sequence of events in an app. Per the installation instructions, the versions table should be created before the app is started. I must be missing something.

This works for a single developer, but how would one share the Rails app with another developer or setup a CI server? You need to create and setup the database, usually through a command like `rails db:schema:load`. This loads the Rails environment, including the models, which is where the `limit` option fails.

> I'm able to install PT (12.0) in a new rails app (6.1) and run some basic version-related tests. Can you provide a series of steps, starting with rails new, that demonstrates the issue?

The steps to recreate:

1. Create a new Rails app
2. Setup paper trail as shown in the readme
3. Drop the database
4. Recreate it with `rails db:create db:schema:load`

**Comment by jaredbeck** [comment]
> The steps to recreate ..

I followed these steps, including `db:schema:load`, but did not observe an error.

> I believe there is something in the app I'm working on pre-loading the models which is causing this issue. So it's specific to my setup. 

Sounds like you're onto something.

> You can close this ticket if you want, but it still might be nice if the class-level code did not depend on the database tables.

Looking at the stack trace from the error produced by your script:

```
..
16: from pt_issue_1307.rb:39:in `<class:User>'
15: from .../paper_trail/has_paper_trail.rb:68:in `has_paper_trail'
14: from .../paper_trail/model_config.rb:120:in `setup'
13: from .../paper_trail/model_config.rb:150:in `check_presence_of_item_subtype_column'
12: from .../paper_trail/version_concern.rb:25:in `item_subtype_column_present?'
..
```

It seems that `check_presence_of_item_subtype_column` is simply an assertion, to provide a helpful error message.

> To use PaperTrail's per-model limit in your %s model, you must have an
> item_subtype column in your versions table. See documentation sections
> 2.e.1 Per-model limit, and 4.b.1 The optional item_subtype column.

> .. it still might be nice if the class-level code did not depend on the database tables.

To remove this dependency, I'd be OK moving this assertion from class-level ("boot time") to runtime.

Then again, the dependency is not really unreasonable, in my mind. If you're going to `load` your models, the database *should* exist.

So, contributions .. welcome? :grin:

**Comment by PhilCoggins** [comment]
We also encountered this issue, I agree with @ryanb that class-level macros should not trigger schema loading by querying your database.

> Then again, the dependency is not really unreasonable, in my mind. If you're going to load your models, the database should exist.

If this were the case, then how would you `rails db:create` in a CI environment, where you are most-likely eager loading your code?

I'd be happy to submit a patch for this, but I would remove the check altogether and rely on a runtime exception, or the exception can be rescued and warn that the `limit` option cannot be used without `item_subtype`, I really don't like the idea of PaperTrail querying my database every time I start my app.

**Comment by jaredbeck** [comment]
>> To remove this dependency, I'd be OK moving this assertion from class-level ("boot time") to runtime.

> I'd be happy to submit a patch for this, but I would remove the check altogether and rely on a runtime exception, or the exception can be rescued and warn that the `limit` option cannot be used without `item_subtype` ..

Thanks Phil, that's fine. The important thing is for the user to get a helpful error when they are missing a required column. If it happens at runtime instead of "boot time", that's fine with me.

**Comment by PhilCoggins** [comment]
@jaredbeck I took a look at this and I'm confused why `item_subtype` is actually required. `enforce_version_limit!`, asks `version_limit` for a limit that's either globally specified or specific to that model (which could be a subclass). Since I'm in an `after_create`, I already have access to the item and its class from the association cache.

```ruby
    def version_limit
      if self.class.item_subtype_column_present?
        klass = (item_subtype || item_type).constantize
        if klass&.paper_trail_options&.key?(:limit)
          return klass.paper_trail_options[:limit]
        end
      end
      PaperTrail.config.version_limit
    end
```

Could simply be:
```ruby
    def version_limit
      item.class.paper_trail_options[:limit] || PaperTrail.config.version_limit
    end
```

Surely I'm missing something?

**Comment by srbartlett** [comment]
Same issue using a class-level macro like this:

```
  has_paper_trail on: [:update, :touch], limit: 5, versions: { scope: -> { order("id desc") } }
```

However, in my scenario the DB actually exists.   I only saw this issue from my Sidekiq instance.   Something related to Sidekiq?  - I didn't find the root cause but this commit fixed it.  Thanks.
