### ISSUE TITLE
Release a new version on Rubygems

### ISSUE THREAD

**Issue by seanfcarroll** [paper-trail-gem/paper_trail#1311]
Hello, I noticed the [last version on Rubygems](https://rubygems.org/gems/paper_trail_manager
) is quite old 

> 0.6.0 - September 18, 2015 (43 KB)

This is quite a useful gem, and chance of pushing a new release?

I'm currently pointing to master

> gem 'paper_trail_manager', github: 'fusion94/paper_trail_manager'

**Comment by aried3r** [comment]
Hey @seanfcarroll, as far as I know the `paper_trail_manager` gem and this gem, `paper_trail`, are not directly associated. I saw that you already opened [an issue on `paper_trail_manager`'s issue tracker](https://github.com/fusion94/paper_trail_manager/issues/36), but I don't think we can directly influence their release schedule.

**Comment by seanfcarroll** [comment]
Oh sorry! I need coffee!! ☕
