### ISSUE TITLE
Add support for separating retention of changes from retention of full object versions to reduce storage requirements

### ISSUE THREAD

**Issue by jdejong** [paper-trail-gem/paper_trail#1313]
Using paper_trail we have found it easy for some version models to amass an extremely large amount of data. For example, we have a model that has about 55 changes on average per object. This model currently has approximately 5 GB of data stored in the table, but the versions table has almost 400 GB. We need to maintain the list of changes that were made for compliance reasons (ie the who and what which includes object_changes) but we only need to keep a couple of full objects around for restoration. Additionally, if needed we could replay backward the object_changes to restore a newer object to an older state. This would greatly reduce our storage requirements while only minimally impacting functionality.

### The Solution

To do this, we would add a new version_changes_limit config element which would be used in combination with the existing version_limit configuration to limit the number of versions stored with either the object, object_changes or both in place.

```
Limit: 4 versions per record with full objects (3 most recent, plus a `create` event), and maintain all versions with changes
PaperTrail.config.version_limit = 3
PaperTrail.config.version_changes_limit = nil
```

```
No limit on versions, all will contain data in object or object_changes 
PaperTrail.config.version_limit = nil
PaperTrail.config.version_changes_limit = nil
```

As with `version_limit` currently, `version_changes_limit` will be set to unlimited by default.

#### Versions/Versions List

To the versions class stub we will add an additional method `.full?` which will return true if object is set for that version
We will additionally have an additional method `.incremental?` which will return true if object_changes is set.

#### Reify

For now Reify will return nil using the default behavior if there is not a full version to restore of the selected version.

### Alternatives considered

Alternately we had considered storing changes in a separate model and utilize an event sourcing strategy for maintaining history. Currently, there is a gem, RailsEventStore, that provides a service bus interface that could be used to build event sourcing which could be used to maintain this same state. The issue is this would require the user to define all events they wish to log, publish them to the EventStore and then build a consumer that would subscribe to those events and then store those events in the database. This may be the preferred method for some, but this overhead seems a bit extreme just to be able to reduce storage while meeting compliance requirements.

### Expectations
Our team would like to develop this feature and merge this functionality into the main branch, however, we do not want to implement this approach unless it is something that would be considered. Otherwise, we will pursue an alternative implementation or approach.

**Comment by ThomasOwens** [comment]
My use case is very similar. I need to maintain the list of changes for nearly every model, but I only want to keep versions (in some cases all versions, in others perhaps only a subset of versions) for select models. This goes to the difference between auditing and versioning.

It doesn't look like this is a supported use case for Paper Trail now, and I'm not sure if it fits into the overall vision.

**Comment by jdejong** [comment]
Thanks @ThomasOwens We are almost done with an implementation of this. Just working on adding relevant tests. Hopefully, they will consider it as a new feature in Paper Trail once it is complete!

**Comment by ThomasOwens** [comment]
@jdejong I was wondering if there were any updates. Are the proposed changes (even if not yet complete) somewhere for public viewing and use? Or were there problems encountered that make it not viable? I'm just curious where this proposed change lands since it's rather important to me and I'm not aware of any other similar gem to paper_trail that has this functionality now. Even if it's not complete, I'd like to take a look and at least learn from what you're trying.

**Comment by jdejong** [comment]
Hi @ThomasOwens we are almost complete this feature PR. We ran into some issues in the test stack and are working to ensure that existing tests all pass even with the new functionality. Hopefully, we can finish this up in the next week or two and get the PR in for people to start looking at. Candidly I was hoping we would have some thought/buy in by the maintainers of paper_trail, but I guess that will have to wait for the PR.

**Comment by ThomasOwens** [comment]
Thank you for the update, @jdejong. I'll be waiting for that branch to look at. Hopefully this gets buy-in from the maintainers as well.

**Comment by ThomasOwens** [comment]
@jdejong I see that this issue has been marked stale. Do you have a fork or branch that can be shared? Even if it's incomplete, understanding the current state and any remaining issues blocking completion would be helpful to myself or anyone else who may want to try to get it to a stable and finished state to open a PR into this gem.

**Comment by jdejong** [comment]
@ThomasOwens We ran into an issue. Out original design to not make this an enablement but something that you could just tweak with config. Unfortunately, we broke a lot of the tests doing this, which in turn would break a lot of users' installs. So we have engineered an enablement flag and are just working on building the tests. One of our senior engineers took this on from me, let me check in with where he is at with this.

**Comment by jaredbeck** [comment]
> This model currently has approximately 5 GB of data stored in the table, but the versions table has almost 400 GB. 

I'm interested in having better solutions for this pain point, generally. I'm not sure what the correct solution is yet. Different applications may require different solutions. 

- `version_limit` is sufficient in many cases (not here)
- [Custom version classes](https://github.com/paper-trail-gem/paper_trail#6a-custom-version-classes) allow sharding of version tables. This technique allows storing version records in a separate database, or even multiple databases.
- A scheduled background job could move version records from "hot" storage (the database) to "cold" storage, like S3.

This proposal, `version_changes_limit`, is interesting. Maybe there's a more general solution though. Maybe we should have a "hook", like [object_changes_adapter](https://github.com/paper-trail-gem/paper_trail#6c-custom-object-changes) that would allow different applications to have different retention policies.

**Comment by logankeenan** [comment]
> [Custom version classes](https://github.com/paper-trail-gem/paper_trail#6a-custom-version-classes) allow sharding of version tables. This technique allows storing version records in a separate database, or even multiple databases.

It looks like [Multiple Database Support](https://guides.rubyonrails.org/active_record_multiple_databases.html) requires `self.abstract_class = true` which wouldn't be [compatible](https://github.com/paper-trail-gem/paper_trail/blob/94e167b5ac95b2ead6999f88397dad01264d0cb5/lib/paper_trail/model_config.rb#L12) with custom version classes. Perhaps, I'm misunderstanding how Paper Trail could be configured.

**Comment by logankeenan** [comment]
> [Custom version classes](https://github.com/paper-trail-gem/paper_trail#6a-custom-version-classes) allow sharding of version tables. This technique allows storing version records in a separate database, or even multiple databases.

Ignore my comment above.  The configuration would look like the code below. I have a `versions` database defined in my database.yml file

```ruby
class Version < ActiveRecord::Base
  include PaperTrail::VersionConcern
  self.abstract_class = true
  connects_to database: { writing: :versions, reading: :versions }
end


class AnimalVersion < Version
  self.table_name = :animal_versions
end

class Animal < ActiveRecord::Base
  has_paper_trail versions: { class_name: 'AnimalVersion' }
end
```
