### ISSUE TITLE
Travis-CI: Ruby 3 build 

### ISSUE THREAD

**Issue by tilo** [paper-trail-gem/paper_trail#1315]
Can you please configure a Ruby 3.0.0 build for Travis-CI?

**Comment by gurgelrenan** [comment]
Hi @tilo . Travis CI was replaced by Github Actions here https://github.com/paper-trail-gem/paper_trail/pull/1276. So at the moment we don't use Travis CI in Paper Trail.

**Comment by tlynam** [comment]
I'm not sure if you can see it @tilo, but here's an example Ruby 3 build
https://github.com/paper-trail-gem/paper_trail/runs/2871873660
