### ISSUE TITLE
Add a last_version association to help against N+1

### ISSUE THREAD

**Issue by Hugo-Hache** [paper-trail-gem/paper_trail#1316]
### Problem description

Solve the N+1 when serializing attributes of the last version is not trivial.

```ruby
class Widget < ActiveRecord::Base
  has_paper_trail
end

class WidgetsController < ApplicationController
  def index
    @widgets = Widget.all
    render json: @widgets.map { |w| {id: w.id, last_editor: w.versions.last.whodunnit} } # Triggers N+1
  end
end
```

### Proposed solution

Add a `has_one :last_version` relation in `model_config` along `versions` :
```ruby
def define_has_one_last_version(options)
  options = ensure_versions_option_is_hash(options)
  check_version_class_name(options)
  check_versions_association_name(options)
  scope = -> { order(created_at: :desc) }
  @model_class.has_one(
    @model_class.versions_association_name,
    scope,
    class_name: @model_class.version_class_name,
    as: :item,
    **options[:versions].except(:name, :scope)
  )
end
```

On our example we can then simply include last_version to fix the N+1:
```ruby
  def index
    @widgets = Widget.all.includes(:last_version)
    render json: @widgets.map { |w| {id: w.id, last_editor: w.last_version.whodunnit} } # N+1 solved
  end
```

### Alternative solution

Introduce a README section "Solving N+1" explaining how a `has_one` can help to solve the issue.

**Comment by tlynam** [comment]
Thank you for opening this issue!  It's an interesting idea to define this association.  I feel like I'm missing something.  How does having a `has_one` association prevent n+1 queries?  I would think we would need to use `includes` or use multiple queries?

Something like using `includes`?
`@widgets = Widget.includes(:versions).all`

Or use multiple queries like:
`PaperTrail::Version.where(item_id: @widgets.map(&:id), item_type: "Widget").pluck(:whodunnit)`

**Comment by Hugo-Hache** [comment]
Exactly this has_one association is only a help to solve the N+1 with the `includes` method. You can spot the difference in the first line of the index method in the examples of the issue description.  

Without last_version
```
  def index
    @widgets = Widget.all
    render json: @widgets.map { |w| {id: w.id, last_editor: w.versions.last.whodunnit} } # Triggers N+1
  end
```

With last_version
```
  def index
    @widgets = Widget.all.includes(:last_version)
    render json: @widgets.map { |w| {id: w.id, last_editor: w.last_version.whodunnit} } # N+1 solved
  end
```

Your second proposition with a second request could as well help to solve the N+1, it would though requires a bit of refinement as currently it's returning all the versions and not only the last, something like:
```
last_version_per_id = PaperTrail::Version
                                    .where(item_id: @widgets.map(&:id), item_type: "Widget")
                                    .group_by(&:item_id)
                                    .transform_values { |v| v.last } # if already ordered by created_at
```

And then in your controller you could use this hash:
```
  def index
    @widgets = Widget.all
    last_version_per_id = PaperTrail::Version
                                        .where(item_id: @widgets.map(&:id), item_type: "Widget")
                                        .group_by(&:item_id)
                                        .transform_values { |v| v.last } # if already ordered by created_at

    render json: @widgets.map { |w| {id: w.id, last_editor: last_version_per_id[w.id].whodunnit} } # N+1 solved
  end
```

**Comment by jaredbeck** [comment]
Hi Hugo, thanks for the proposal. Thanks for reviewing, Todd.

> ```
>   render json: @widgets.map { |w| {id: w.id, last_editor: w.versions.last.whodunnit} } # Triggers N+1
> ```

Using SQL, it is easy to avoid this N+1 problem:

```sql
select whodunnit 
from versions v
inner join widgets w on w.id = v.item_id
  and w.item_type = 'Widget'
```

In ActiveRecord, this would be

```ruby
Widget.joins(:versions).pluck(:whodunnit)
```

Unless I'm missing something, I don't think we need the proposed feature.

**Comment by Hugo-Hache** [comment]
Indeed with the joins you get the versions, except you will have one row per version. For instance if you have 2 widgets with 3 versions each, you will get 6 results. 


Unfortunately adding a distinct here won't work if you select a column from the version (as the rows won't be distinct anymore). So you would need to deduplicate manually with something like:

``` ruby
Widget
  .joins(:versions)
  .select('anomalies.*', 'versions.updated_at AS version_updated_at ', 'whodunnit')
  .group_by(&:id)
  .map { |rows| rows.max_by(&:version_updated_at) }
  .map { |w| [w.title, w.whodunnit] }
```
I'm no SQL wiz but I think joining only the last version would go through a subrequest. Feasible, but not that straightforward. 
Let me know if something needs more explanation, I agree this subject obvious.
