### ISSUE TITLE
Retroactive ObjectChanges creation

### ISSUE THREAD

**Issue by bh8ur8js** [paper-trail-gem/paper_trail#1319]
Thank you for your contribution!

Due to limited volunteers, issues that do not follow this template will be
closed without comment.

**Is your feature suggestion related to a problem? Please describe.**

ObjectChanges is very very useful feature, I would suggest the it included as the default. If it is enabled after use, the column is null. It would be very useful to be able to retroactively generate the ChangeSets from the versions already stored.

**Describe the solution you'd like to build**

A rake task, that updates ObjectChanges which are null, ie those records created prior to the object change tracking being enabled based on the full Object Versions stored. ie running the current process but modifying it to run on historical versions to create the changeset data.

**Describe alternatives you've considered**

I am not skilled enough to do this myself.

**Comment by tlynam** [comment]
Thank you @bh8ur8js for opening this!  This sounds interesting and useful.  I'm not too familiar with this area of the code and don't know how easy this would be.  Due to limited volunteer time, I think we need someone to investigate and open a PR.

**Comment by bh8ur8js** [comment]
@tlynam All the methods are already there

I think the process would go like this.

for each version record with null changeset
      get all versions of that Object ordered
         reify object and next version 
           calc/set changeset ( it is what happens now on update so calling the same method should work) 

All we would be doing is passing the reify objects manually
   version n compare version n+1 set changeset 

I think a rake task would do the job.
