### ISSUE TITLE
Superclass mismatch for class Version

### ISSUE THREAD

**Issue by Svashta** [paper-trail-gem/paper_trail#1321]
I've updated my bundle today. In DEV it seems fine, but when deployed to PROD (apache+passenger) i am getting this:

superclass mismatch for class Version (TypeError)
  /path/to/my/app/releases/20210616074449/app/models/paper_trail/version.rb:2:in `<module:PaperTrail>'

**Comment by tlynam** [comment]
Hi @Svashta, thank you for opening this issue!  Is this the same issue mentioned in https://github.com/paper-trail-gem/paper_trail/pull/1237#issuecomment-616532443?  If we're going to work on a solution, it would be helpful to utilize the bug template https://github.com/paper-trail-gem/paper_trail/blob/master/.github/ISSUE_TEMPLATE/bug-report.md.

**Comment by fryertom44** [comment]
I solved this issue by deleting the auto-generated 'Version' class. The newer versions of PaperTrail use mixins for inheriting the version functionality, so the auto-generated Version class is now redundant. I guess if you want to use a superclass you can still roll your own, but be sure to call it something other than 'Version'.
