### ISSUE TITLE
Few links out of date / not found in README

### ISSUE THREAD

**Issue by aquaflamingo** [paper-trail-gem/paper_trail#1325]
Hi friends,

I noticed that some sections of the README with hyperlinks to other repos are broken and responding with 404. For example in [3c Diffing](https://github.com/paper-trail-gem/paper_trail/#3c-diffing-versions) both these repositories no longer exist:

http://github.com/jeremyw/paper_trail/blob/master/lib/paper_trail/has_paper_trail.rb#L151-156
http://github.com/tim/activerecord-diff

Happy to put a PR to update the README, but, thought I would check first to see what folks thought?

**Comment by gurgelrenan** [comment]
Hi @robertsimoes , PRs are welcome! 😄
