### ISSUE TITLE
if and unless options are ignored on touch

### ISSUE THREAD

**Issue by stahor** [paper-trail-gem/paper_trail#1326]
I'm unsure whether it's a new feature or a bug fix. As you can see in the code below paper_trail `on_touch` does not run the same checks as for update or create.
https://github.com/paper-trail-gem/paper_trail/blob/49659e8a0c4cb0c80aeab344b7b434de7f057c88/lib/paper_trail/model_config.rb#L108-L116
https://github.com/paper-trail-gem/paper_trail/blob/49659e8a0c4cb0c80aeab344b7b434de7f057c88/lib/paper_trail/model_config.rb#L79-L97

It feels like we need `if r.paper_trail.save_version?` check for the on_touch callback either.

**Comment by stahor** [comment]
Also, this code does not create a new version on touch in my rails-6.1.3.2 app. Though, I'm not yet sure that whether or not it's intended. Setting force: true fixes the issue.

**Comment by yrashk** [comment]
I am also interested in figuring this out; I am trying to avoid saving a new version if the object was touched and nothing was changed (this creates pointless versions that have nothing but `updated_at` updated)
