### ISSUE TITLE
The versions doesn't create when associated object deleted since v12.1.0. 

### ISSUE THREAD

**Issue by y-yagi** [paper-trail-gem/paper_trail#1339]
Check the following boxes:

- [x] This is not a usage question, this is a bug report
- [x] This bug can be reproduced with the script I provide below
- [x] This bug can be reproduced in the latest release of the `paper_trail` gem

Our application have a model that have an association with `touch: true` option. Before v12.1.0, when deleting the model, `touch` event triggered and created an version of an  association. But v12.1.0, association's version isn't created.  

Reproduction script is following. 

```ruby 
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "6.0.4.1"
  gem "paper_trail", "12.1.0", require: false
  # gem "paper_trail", "12.0.0", require: false
  gem "sqlite3"
  gem "minitest"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = nil

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name, null: false
    t.timestamps
  end

  create_table :avatars, force: true do |t|
    t.string :name, null: false
    t.belongs_to :user, null: false
    t.timestamps
  end

  create_table :versions do |t|
    t.string :item_type, null: false
    t.integer :item_id, null: false
    t.string :event, null: false
    t.string :whodunnit
    t.text :object, limit: 1_073_741_823
    t.text :object_changes, limit: 1_073_741_823
    t.datetime :created_at
  end
  add_index :versions, %i[item_type item_id]
end

ActiveRecord::Base.logger = Logger.new(STDOUT)

require "paper_trail"

class User < ActiveRecord::Base
  has_paper_trail
end

class Avatar < ActiveRecord::Base
  has_paper_trail

  belongs_to :user, touch: true
end

class BugTest < ActiveSupport::TestCase
  # This test passed with v12.0.0, but doesn't pass with v12.1.0.
  def test_1
    user = User.create(name: "Jane")
    avatar = Avatar.create(name: "Dummy1", user: user)

    assert_difference(-> { PaperTrail::Version.count }, +2) {
      Avatar.destroy_all
    }
  end
end
```

Is this intentional change? 

Thanks.

**Comment by jaredbeck** [comment]
Hi Yagi-san, thanks for the excellent issue script.

> Is this intentional change?

I'm fairly certain this change is due to https://github.com/paper-trail-gem/paper_trail/pull/1285. The tests in that PR don't cover this scenario. @quainjn, @westonganger, and @tlynam: should we treat this as a bug?

**Comment by y-yagi** [comment]
OK. I found that this is caused by Rails. The changes that `touch` from  association can't get via dirty methods.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord"
  gem "sqlite3"
  gem "minitest"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = nil

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name, null: false
    t.timestamps
  end

  create_table :avatars, force: true do |t|
    t.string :name, null: false
    t.belongs_to :user, null: false
    t.timestamps
  end
end

class User < ActiveRecord::Base
end

class Avatar < ActiveRecord::Base
  belongs_to :user, touch: true
end

class BugTest < ActiveSupport::TestCase
  def test_1
    user = User.create(name: "Jane")
    avatar = Avatar.create(name: "Dummy1", user: user)
    avatar = Avatar.first

    avatar.touch

    assert_not_equal user.updated_at, user.reload.updated_at
    assert_not_empty avatar.saved_changes
    assert_not_empty avatar.user.saved_changes
  end
end

```

Before #1285, thanks to `force` option, version created in every case. But now `force` is false , and `changed_notably?` is also false because of the Rails bug, so version doesn't create.

**Comment by jaredbeck** [comment]
> OK. I found that this is caused by Rails.

Thanks. Would you like to close this, or are you thinking about implementing a workaround in PT?

**Comment by jenrzzz** [comment]
Is there a Rails issue for the breaking change? Just for context. I imagine they won't be undoing any of the Dirty behavior changes.

**Comment by y-yagi** [comment]
@jaredbeck I'm trying to implement a workaround in PT, but I can't come up with good solution. How do you feel about adding a config to control this behavior? 

@jenrzzz To clearity, this is a breaking change of PT, not Rails. But the base cause is on Rails side and I don't create an issue yet.

**Comment by y-yagi** [comment]
I've created a PR to fix this. #1376.
