### ISSUE TITLE
reifying a "destroy" version should return a "destroyed" record

### ISSUE THREAD

**Issue by tsujigiri** [paper-trail-gem/paper_trail#1352]
I'm trying to compare different versions at specific points in time and I keep running into this issue. Reifying a _destroying_ version and then calling `version_at` with a timestamp from after the record got destroyed, should return `nil`. Instead it returns the reified record. This is because `version_at` calls `@record.destroyed?`, which returns false.

A simple fix would be to set the record's `@destroyed` instance variable to true, when instantiating it in the reifier, but I'm not sure if this is a desirable solution, as it meddles with ActiveRecord interna and there doesn't seem to be an API for doing that.

I [forked](https://github.com/paper-trail-gem/paper_trail/compare/master...ComboStrikeHQ:destroyed-record-fix) `paper_trail` (version < 12, so it works with PT-AT) and the above solution seems to fix the problem for me.

**Comment by jaredbeck** [comment]
We try to only use the public API of ActiveRecord. I'm sure you are correct that the instance variable is considered private. If you can think of a solution that uses public API, a PR would be welcome.
