### ISSUE TITLE
Generated CreateVersions migration does not respect Standard

### ISSUE THREAD

**Issue by Vin0uz** [paper-trail-gem/paper_trail#1353]
👋  First, thank you for the amazing work!

Today, I noticed that the generated `CreateVersions` migration does not respect [Standard](https://github.com/testdouble/standard) convention, hence breaking automated linters.

I know, I know, that's our problem not the gem's one. I just wondered if you shared Standard pov about having such a unique convention, and if yes, may I propose a diff to fix that migration ?

Not much would be changed, here's the list of linters that were triggered : 
- Layout/EmptyLinesAroundClassBody
- Layout/ExtraSpacing
- Layout/SpaceInsideHashLiteralBraces
- Style/PercentLiteralDelimiters

If you agree with it, I'll propose you a diff to edit this and allow anyone to generate without breaking `Standard` 🙌

**Comment by jeremy-ebler-vineti** [comment]
I don't think you'll be able to persuade every project out there to adopt your preferred style guide. I'd just call `my_favorite_linter --fix` and call it a day.

Before this, I hadn't heard of [TestDouble's Standard](https://github.com/testdouble/standard). Today is has 1.8k stars on Github, which isn't bad. However, [Airbnb's Rubocop rules](https://github.com/airbnb/ruby/tree/master/rubocop-airbnb) have 3.4k stars, nearly twice as many. There are many other rulesets, I'm sure. I don't think it's possible to make everyone happy regarding where to have whitespace and where to not have whitespace, but it's easy for everyone to `--fix` and commit the migration using whatever style their project prefers.

**Comment by jaredbeck** [comment]
Hi Vinhas, thanks for the suggestion. This project uses RuboCop. I'm happy with it. As Jeremy says, you can use your preferred formatter after the migration is generated.
