### ISSUE TITLE
Disallow installation with incompatible Rails versions

### ISSUE THREAD

**Issue by mvz** [paper-trail-gem/paper_trail#1360]
Many projects rely on CI to check if updating the version of a dependency will lead to problems. The current policy of PaperTrail to not enforce its upper Rails version dependency means that CI will run fine and possible result in a succesful run because possibly incompatible corner cases are not tested by the project depending on PaperTrail. Having a green CI run means such a dependency update could get merged prematurely.

In particular, it is annoying that Dependabot creates a pull requests to migrate to Rails 7 when one of my dependencies is in fact incompatible.

I'd like PaperTrail to declare its upper Rails dependency in the gemspec. I'm aware of the reasoning in`lib/papertrail/compatibility.rb`, but I think Contributors who want to work on compatibility with a new Rails version can simply adjust the version in the gemspec as part of the pull request, just like they need to adjust the upper version in `lib/papertrail/compatibility.rb` currently (https://github.com/paper-trail-gem/paper_trail/pull/1356/files#diff-5d04ddf11d7b7ed8162627b3985e3f41bb489cbf0ed0a065cb711d2bdd10042fR21).

An alternative would be for PaperTrail to raise an error for incompatible versions, unless PT_SILENCE_AR_COMPAT_WARNING is set.

**Comment by jaredbeck** [comment]
This was discussed thoroughly in https://github.com/paper-trail-gem/paper_trail/pull/1213. I continue to be encouraged that it was the right decision for two main reasons. First, many other important gems like devise, carrierwave, and sidekiq had made the same decision. Secondly, removing the upper bound has encouraged contributions like https://github.com/paper-trail-gem/paper_trail/pull/1356
