### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by AlfonsoUceda** [paper-trail-gem/paper_trail#1362]
Hi folks,

Are you planning to release a new version of paper_trail for supporting ruby 3.1 and rails 7? Would it be possible to make a new release for ruby 3.1?

Thanks for your amazing work.

**Comment by jaredbeck** [comment]
I'd like to give https://github.com/paper-trail-gem/paper_trail/pull/1356 another week or two, so I can release both together. Please use `gem .. git:` in the meantime.

**Comment by jaredbeck** [comment]
12.2.0 released
