### ISSUE TITLE
squashing versions

### ISSUE THREAD

**Issue by koenhandekyn** [paper-trail-gem/paper_trail#1372]
## auto save creating many versions within very short periods

we have apps where we have auto save (think google sheets or similar).
also in some other we apps we have auto save for forms.

nice for the user but it kind of screws up the audit / version trail.

## squashing versions to the rescue

we have build a little task that finds related changesets and squashes them post factum into single changeset, just like if they all happened in one go. if anyone is interested, we can share the snippet.

## suggestion

it would be nice though if papertrail could see 'immediately' that it should merge the version with the previous one. has anyone thought about this? is this a new idea? would it be possible as a 'plugin' ? tips or ideas about this ? e.g. we could configure an entity with 'squash_versions_within 1.minute' and it could be picked up by a papertrail plugin in to auto squash the version. 

curious about your reactions. we can't be the first to think about this ;)

**Comment by koenhandekyn** [comment]
from our rake file, here you go :) 

```
  def merge(v1, v2)
    v1.reify # this is just here for testing if the version is still 'reifiable'
    if v2 && (v2.created_at.to_date == v1.created_at.to_date) && (v2.created_at - v1.created_at) < 60*24
      # algorithm
      #   - turn v2 into a single version that represent the change from prior to v1 up to after v2
      # the object represent the OLD version, the OLD version is the version it was at v1 change
      v2.object = v1.object
      merged_changes = v2.changeset.reduce(v1.changeset) do |merged_changes, (key, change)|
        if merged_changes[key]
          # old change key => [a,b1]
          # new change key => [b2,c]
          # warning if b1 != b2
          Rails.logger.warn "warning transient values don't match for key #{key} value #{merged_changes[key][1].to_s.truncate(20)} vs #{change[0].to_s.truncate(20)}" unless merged_changes[key][1] == change[0] #
          if merged_changes[key][0] != change[1] # if a != c
            # merged[key] = [a,c]
            merged_changes[key] = [merged_changes[key][0], change[1]]
          else # if a == c
            merged_changes.delete(key)
          end
        else
          # just add the change
          merged_changes[key] = change
        end
        merged_changes
      end
      Rails.logger.debug "merging #{v1.item_type} #{v1.id} into #{v2.id} [changes #{v2.changeset.transform_values { |a,b| [a.to_s.truncate(20), b.to_s.truncate(20)] }}]"
      v1.delete
      v2.save!
    end
  end

  desc "squash paper trail versions"
  task squash_paper_trail: [:environment, :clean_paper_trail] do
    versions = PaperTrail::Version.where(event: "update").order(created_at: :asc)
    total = versions.count
    puts "versions ##{total}"
    versions.each_with_index do |v1, index|
      v2 = v1.next
      begin
        merge(v1, v2)
        puts Time.now.to_s + " left ##{total-index} - current #{v1.item_type} #{v1.item_id}"
      rescue StandardError => error
        puts
        puts "error deserializing, skipping due to #{error}"
        puts v1.inspect
      end
    end
  end
```

**Comment by russexist** [comment]
> from our rake file, here you go :)
> 
> ```
>   def merge(v1, v2)
>     v1.reify # this is just here for testing if the version is still 'reifiable'
>     if v2 && (v2.created_at.to_date == v1.created_at.to_date) && (v2.created_at - v1.created_at) < 60*24
>       # algorithm
>       #   - turn v2 into a single version that represent the change from prior to v1 up to after v2
>       # the object represent the OLD version, the OLD version is the version it was at v1 change
>       v2.object = v1.object
>       merged_changes = v2.changeset.reduce(v1.changeset) do |merged_changes, (key, change)|
>         if merged_changes[key]
>           # old change key => [a,b1]
>           # new change key => [b2,c]
>           # warning if b1 != b2
>           Rails.logger.warn "warning transient values don't match for key #{key} value #{merged_changes[key][1].to_s.truncate(20)} vs #{change[0].to_s.truncate(20)}" unless merged_changes[key][1] == change[0] #
>           if merged_changes[key][0] != change[1] # if a != c
>             # merged[key] = [a,c]
>             merged_changes[key] = [merged_changes[key][0], change[1]]
>           else # if a == c
>             merged_changes.delete(key)
>           end
>         else
>           # just add the change
>           merged_changes[key] = change
>         end
>         merged_changes
>       end
>       Rails.logger.debug "merging #{v1.item_type} #{v1.id} into #{v2.id} [changes #{v2.changeset.transform_values { |a,b| [a.to_s.truncate(20), b.to_s.truncate(20)] }}]"
>       v1.delete
>       v2.save!
>     end
>   end
> 
>   desc "squash paper trail versions"
>   task squash_paper_trail: [:environment, :clean_paper_trail] do
>     versions = PaperTrail::Version.where(event: "update").order(created_at: :asc)
>     total = versions.count
>     puts "versions ##{total}"
>     versions.each_with_index do |v1, index|
>       v2 = v1.next
>       begin
>         merge(v1, v2)
>         puts Time.now.to_s + " left ##{total-index} - current #{v1.item_type} #{v1.item_id}"
>       rescue StandardError => error
>         puts
>         puts "error deserializing, skipping due to #{error}"
>         puts v1.inspect
>       end
>     end
>   end
> ```

Thanks)

**Comment by russexist** [comment]
Thanks)

**Comment by fameoflight** [comment]
Thanks @koenhandekyn I modified the code for my purpose to seperate out logic where it's merged. Sharing in hope someone find it useful 

```ruby

module PaperTrail
  module SquashHelpers
    extend ActiveSupport::Concern

    class NonConsecutiveChanges < StandardError
    end

    def squash_versions(from_version, to_version)
      copy_attributes(from_version, to_version)

      to_version.save!

      from_version.delete

      to_version
    end

    private

    def copy_attributes(from_version, to_version)
      from_version.reify # this is just here for testing if the version is still 'reifiable'

      return nil if from_version.class != to_version.class

      # algorithm
      #   - turn to_version into a single version that represent the change from prior to from_version up to after to_version
      # the object represent the OLD version, the OLD version is the version it was at from_version change
      to_version.object = from_version.object

      to_version.object_changes = _internal_merge_changeset(from_version, to_version)

      # copy over whodunit
      to_version.whodunnit = to_version.whodunnit || from_version.whodunnit
    end

    def _internal_merge_changeset(from_version, to_version)
      merged_changes = from_version.changeset

      to_version.changeset.each do |key, change|
        # this change doesn't exist in previous version
        unless merged_changes[key]
          merged_changes[key] = change
          next
        end

        # these are non consective version, merging them will break version history
        raise NonConsecutiveChanges unless merged_changes[key][1] == change[0]

        if merged_changes[key][0] == change[1]
          # value didn't change between from_version and version 2, delete the change
          merged_changes.delete(key)
        else
          merged_changes[key] = [merged_changes[key][0], change[1]]
        end
      end

      merged_changes
    end
  end
end
```
