### ISSUE TITLE
frameworks/rspec inclusion leaks state between examples

### ISSUE THREAD

**Issue by Darhazer** [paper-trail-gem/paper_trail#1386]
# Description

frameworks/rspec defines before(:each) hooks that leak state.
The paper trail is being disabled, and than enabled if `versioning: true` is provided, and not restored to the previous state afterwards. This makes for flaky tests, as whether PaperTrail is enabled or not in a `before(:all)` hooks now depends on whether it was enabled in the last run example. 

This could be resolved by providing `after(:each)` which would disable again (or just using `around(:each)` for the branch that has versioning enabled, to restore to the previous value. Note that `with_versioning` helper essentially does that, restoring to the previous value.

# Reproduction
```
require 'paper_trail/frameworks/rspec'

RSpec.describe 'hook flakiness' do
  context 'with versioning disabled', versioning: false do
    it 'works as expected' do
      expect(PaperTrail.enabled?).to be_falsy
    end
  end

  context 'with versioning enabled', versioning: true do
    it 'works as expected' do
      expect(PaperTrail.enabled?).to be_truthy
    end
  end

  context 'with no paper trail configuration' do
    before(:all) do
      expect(PaperTrail.enabled?).to be_truthy
    end

    it 'works as expected' do
      expect(PaperTrail.enabled?).to be_falsy
    end
  end
end
```

Now if this is run in exact order, it passes, as `with versioning enabled` leaks state:
```
 rspec spec/paper_trail_spec.rb -fd --order defined 

hook flakiness
  with versioning disabled
Disabling paper trail
    works as expected
  with versioning enabled
Disabling paper trail
Enabling paper trail
    works as expected
  with no paper trail configuration
Disabling paper trail
    works as expected

Finished in 0.0135 seconds (files took 4.26 seconds to load)
3 examples, 0 failures
```

But let's run subset of the examples:
```
rspec spec/paper_trail_spec.rb:4:16 -fd --order defined
Run options: include {:locations=>{"./spec/paper_trail_spec.rb"=>[4, 16]}}

hook flakiness
  with versioning disabled
Disabling paper trail
    works as expected
  with no paper trail configuration
    works as expected (FAILED - 1)

Failures:

  1) hook flakiness with no paper trail configuration works as expected
     Failure/Error: expect(PaperTrail.enabled?).to be_truthy
     
       expected: truthy value
            got: false
     # ./spec/paper_trail_spec.rb:18:in `block (3 levels) in <main>'

Finished in 0.01448 seconds (files took 4.48 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/paper_trail_spec.rb:21 # hook flakiness with no paper trail configuration works as expected
```

# Additional information 

- [x] This is not a usage question, this is a bug report
- [x] This bug can be reproduced with the script I provide below
- [x] This bug can be reproduced in the latest release of the `paper_trail` gem

PaperTrail version: 12.3.0

**Comment by drewlustro** [comment]
This issue is not stale... I just ran into it today.

Man, `stale-bot` is the bane of open source.
