### ISSUE TITLE
Store encrypted values on object_changes column

### ISSUE THREAD

**Issue by tgsoverly** [paper-trail-gem/paper_trail#1392]
**Is your feature suggestion related to a problem? Please describe.**

Rails 7 encrypted fields have their changes on the object stored in plain text

**Describe the solution you'd like to build**

The serializer stores the encrypted value for the change set.

**Describe alternatives you've considered**

I can't think of one really.  I am assuming you are encrypting values so they won't show up as plain text in the database.

**Comment by Obversity** [comment]
Vaguely relevant: we're using the `lockbox` gem with the `blind_index` gem and for some of our blind indexes so our encrypted columns are searchable. Some of those blind indexes are set using attributes like `attribute :my_attribute, :string`.

These attributes — which we expected to be transient — DO in fact get stored in the database in plain text currently by paper_trail, if you don't do `skip: [:my_attribute]` in the paper_trail config. Just a heads up to anyone thinking about encryption with paper_trail.

**Comment by danbernier** [comment]
I'm having the same issue using [the symmetric-encryption gem](https://rubygems.org/gems/symmetric-encryption) with rails 6.1.*.

If you're considering only rails 7, it'd be tempting to use it to introspect to figure out which columns are encrypted and automatically Do The Right Thing. If you broaden the scope to consider other gems, that widens the scope of introspection and automation, but maybe there's a solution that can be less tightly-bound to rails and still clean.

**Comment by khalilgharbaoui** [comment]
> Vaguely relevant: we're using the `lockbox` gem with the `blind_index` gem to make some of our encrypted columns searchable. Some of those blind indexes are set using Rails' attribute API like so:
> 
> ```
> attribute :my_attribute, :string
> ```
> 
> These attributes — which we expected to be transient — DO in fact get stored in the database in plain text currently by paper_trail, in the `object` and `object_changes` fields, if you don't do `skip: [:my_attribute]` in the paper_trail config. Just a heads up to anyone thinking about encryption with paper_trail.

Additional FYI:
`skip:`, `ignore:` and `only:` do not work when set on Model level, so they really need to be in the paper_trail config in the initializer:
`config/initializers/paper_trail.rb`
```ruby
PaperTrail.config.enabled = true
PaperTrail.config.has_paper_trail_defaults = {
  skip: [:x,:y,:z],
  only: [:a,:b,:c],
  ignore: [:d,:e,:f]
}
```
Not graceful but works. Make sure you check out: https://github.com/paper-trail-gem/paper_trail#1e1-global

**Comment by vccoffey** [comment]
This issue is a blocker for upgrading our application to Rails 7.  I would be open to working on a solution if someone more familiar with paper_trail would pair with me to get started.

**Comment by glennfu** [comment]
@danbernier Have you made any progress with your custom adapter? I'm interested in taking a look at this myself so I'd love to know what you've learned so far.

**Comment by glennfu** [comment]
I just set this up on my Rails 7 project with `--with-changes` and it appears to already be doing a great job with Rails 7 encrypted attributes. I see `object_changes` serializing the entire object like:
```
["object", "---\nid: 1\nname: '{\"p\":\"c8bS\",\"h\":{\"iv\":\"jH293SIPDY4/W3O\",\"at\":\"zIgj96p+aiYyLrdEvWK6w==\"}}'\naddress...
```
Then when I do something like `a.versions.first.changeset` I see it's fetching and `reifying` to build a fake `object.changes` to work with. So I don't think I actually need anything new for native encrypted attributes.

**Comment by danbernier** [comment]
> @danbernier Have you made any progress with your custom adapter? I'm interested in taking a look at this myself so I'd love to know what you've learned so far.

Not really, no - we went a different approach. Part of the solution was to stop tracking changes to SSN, and part of it was to upgrade to rails 7 and encrypt the whole `object` and `object_changes` columns. It's not perfect, but it ameliorated the risk enough that we started worrying about other things.

**Comment by vccoffey** [comment]
If the `object_changes` column is serialized yaml, the encrypted values are stored.  The bug only occurs for Postgres jsonb columns.  I'm working on a fix that I will post here.

**Comment by ferrisoxide** [comment]
Probably not much use to anyone, but we followed @danbernier's approach and just encrypted all-the-things for those classes that need it - i.e. creating a subclass just for encrypting `object` and `object_changes`, ala

```ruby
class EncryptedVersion < PaperTrail::Version
  self.table_name = :versions

  encrypts :object
  encrypts :object_changes
end
```

and then use it as necessary

```ruby
class User < ApplicationRecord
  has_paper_trail versions: {
    class_name: 'EncryptedVersion'
  }
end
```

And then encrypting all the data already in the app:

```ruby
class EncryptSensitiveVersionData < ActiveRecord::Migration[7.0]

  ENCRYPTED_VERSION_TYPES = %w[User].freeze # In our app this was a longer list 
 
  def up
    EncryptedVersion.where(item_type: ENCRYPTED_VERSION_TYPES ).find_each do |version|
      version.encrypt
    end
  end

  def down
    EncryptedVersion.where(item_type: ENCRYPTED_VERSION_TYPES ).find_each do |version|
      version.decrypt
    end
  end
end
```

Probably stating the obvious here. Apologies if so.

**Comment by vccoffey** [comment]
Here's a patch that stores serialized (encrypted) values in postgres json columns, and decrypts them as necessary.
In our app we put this code in `config/initializers/paper_trail.rb`.

```ruby
module PaperTrail
  module AttributeSerializers
    class ObjectAttribute
      def alter(attributes, serialization_method)
        # for columns of type `JSON` on `PostgreSQL` databases,
        # only serialize encrypted columns
        if object_col_is_json?
          encrypted_attributes = @model_class.try(:encrypted_attributes)
          return attributes if encrypted_attributes.blank?

          encrypted_attributes.map!(&:to_s)
        end

        serializer = CastAttributeSerializer.new(@model_class)
        attributes.each do |key, value|
          next if encrypted_attributes&.exclude? key

          attributes[key] = serializer.send(serialization_method, key, attributes[key])
        end
      end
    end
  end
end

module PaperTrail
  module AttributeSerializers
    class ObjectChangesAttribute
      def alter(changes, serialization_method)
        # for columns of type `JSON` on `PostgreSQL` databases,
        # only serialize values for encrypted columns
        if object_changes_col_is_json?
          encrypted_attributes = @item_class.try(:encrypted_attributes)
          return changes if encrypted_attributes.blank?

          encrypted_attributes.map!(&:to_s)
        end

        serializer = CastAttributeSerializer.new(@item_class)
        changes.clone.each do |key, change|
          # `change` is an Array with two elements, representing before and after.
          changes[key] = Array(change).map do |value|
            next(value) if encrypted_attributes&.exclude? key

            serializer.send(serialization_method, key, value)
          end
        end
      end
    end
  end
end
```

**Comment by Nealsoni00** [comment]
Thank you @vccoffey for your amazing answer. A few things to note for anyone else reading this:

1. Papertrail ignores the PaperTrail.serializer = PaperTrail::Serializers::JSON  when the database column for `object` and `object_vrsion` is `json` or `jsonb`
2. I had to put the above code in a `ActiveSupport::Reloader.to_prepare` like below because it was not properly overloading just the `ObjectAttribute` class. 

``` ruby
ActiveSupport::Reloader.to_prepare do
  module PaperTrail # rubocop:disable Lint/ConstantDefinitionInBlock
    module AttributeSerializers
      class ObjectAttribute
        def alter(attributes, serialization_method)
          ## ABOVE CODE
         end
      end
    end
  end

  module PaperTrail # rubocop:disable Lint/ConstantDefinitionInBlock
    module AttributeSerializers
      class ObjectChangesAttribute
        # Serialize or deserialize the `version.object_changes` column.
        def alter(changes, serialization_method)
           ## ABOVE CODE
        end
      end
    end
  end
end
```

**Comment by FunnyHector** [comment]
@vccoffey thank you for providing a solution. This is really helpful. Would you consider making a PR to upgrade paper_trail gem so that people don't need to use a patch?

**Comment by FunnyHector** [comment]
I've added a PR #1422 that hopefully fixes this issue. The idea is from @vccoffey, many thanks to Vern.
