### ISSUE TITLE
Update YAML->JSON suggested solution in `README.md`.

### ISSUE THREAD

**Issue by fr33r** [paper-trail-gem/paper_trail#1394]
Hey there 👋🏼 !

Choosing to file a bug report, as it's unclear whether this project considers incorrect / misleading documentation as a bug.

As currently written, the YAML -> JSON conversion documentation in `README.md` is insufficient in two ways:

1) Somewhat related to https://github.com/rails/rails/issues/43966, usage of `ActiveRecord::Type::Time::Value` to serialize date/time values in Rails 7 not only caused issues for deserializing YAML, it also cannot be directly serialized to JSON:

```
> offender.object
=> "---\ntime: !ruby/object:ActiveRecord::Type::Time::Value\n  utc: 2000-01-01 13:45:00.000000000 Z\n  zone: &1 !ruby/object:ActiveSupport::TimeZone\n    name: Etc/UTC\n  time: 2000-01-01 13:45:00.000000000 Z\ntimezone: America/Los_Angeles\n"
> time = YAML.load(offender.object)["time"]
> time.to_json
/opt/rubies/ruby-3.0.3/lib/ruby/3.0.0/delegate.rb:405:in `__getobj__': not delegated (ArgumentError)
```

I propose the documentation suggests loading date/time values as `ActiveSupport::TimeWithZone` by specifying the appropriate YAML load tag:

```rb
::YAML.load_tags['!ruby/object:ActiveRecord::Type::Time::Value'] = 'ActiveSupport::TimeWithZone'
```

2. The documentation as is suggested would result in data loss of `object_changes`, because `create` events do not populate `object` but do populate `object_changes`. This is the current documented code snippet:

```rb
PaperTrail::Version.where.not(object: nil).find_each do |version|
  version.update_column(:new_object, YAML.load(version.object))

  # if version.object_changes
  #   version.update_column(
  #     :new_object_changes,
  #     YAML.load(version.object_changes)
  #   )
  # end
end
```

And the proposed code snippet would be:

```rb
PaperTrail::Version.find_each do |version|
  version.update_column(:new_object, YAML.load(version.object)) if version.object

  # if version.object_changes
  #   version.update_column(
  #     :new_object_changes,
  #     YAML.load(version.object_changes)
  #   )
  # end
end
```

Checked the following boxes:

- [x] This is not a usage question, this is a (documentation-related) bug report
- [x] ~This bug can be reproduced with the script I provide below~
- [x] ~This bug can be reproduced in the latest release of the `paper_trail` gem~

Due to limited volunteers, we cannot answer *usage* questions. Please ask such
questions on [StackOverflow](https://stackoverflow.com/tags/paper-trail-gem).

**Comment by gurgelrenan** [comment]
Hi @fr33r thanks for your time to open this issue. Could you reproduce this error with a script? I know that you said that is a README update, but it's important that this error that you describe could be put in a test case after someone fix it.

**Comment by ziaulrehman40** [comment]
I dont know if it is related, but i am getting
```
Tried to load unspecified class: ActiveSupport::TimeWithZone
...db/migrate/20240604133914_convert_paper_trail.rb:13:in `block in change'
...db/migrate/20240604133914_convert_paper_trail.rb:11:in `change'

Caused by:
Psych::DisallowedClass: Tried to load unspecified class: ActiveSupport::TimeWithZone
```

Even after TRYING to use the suggestions, i have put the YAML tags line in migrations, will try putting it in config etc
