### ISSUE TITLE
paper_trail:install requires a db connection

### ISSUE THREAD

**Issue by dunn** [paper-trail-gem/paper_trail#1400]
- [x] This is not a usage question, this is a bug report
- [x] This bug can be reproduced with the script I provide below
- [x] This bug can be reproduced in the latest release of the `paper_trail` gem

---

 Rails applications that are run in containers have to be built in advance, without an active DB connection.  `paper_trail:install` doesn't run the migrations, but the `#mysql?` method in the generator relies on `ActiveRecord::Base.connection`, which attempts to initialize a database connection.  This causes image builds to fail.

**Comment by acesuares** [comment]
This is why I made a fork very very long ago: https://github.com/acesuares/paper_trail/commit/170b661e94f42625452e71fb799d1ab4e3b783bc
