### ISSUE TITLE
PaperTrail with Rails 7: history index and history show not showing any data

### ISSUE THREAD

**Issue by AndreiMGagiu** [paper-trail-gem/paper_trail#1407]
<img width="1384" alt="Screenshot 2022-11-18 at 19 08 55" src="https://user-images.githubusercontent.com/43989360/202762723-8d39ae24-804c-425e-b680-0608c524cea7.png">

After upgrading to the latest version of Rails(7) I noticed in my application that the history tab index/show is not displaying the model changes, the page is blank.It was working perfectly fine with the previous rails version(6). Does someone have a workaround for this? Thanks

**Comment by scottbullard** [comment]
You probably need to convert your data to JSON.
See: 
https://github.com/paper-trail-gem/paper_trail/blob/master/CHANGELOG.md#breaking-changes-1
https://github.com/paper-trail-gem/paper_trail/blob/master/doc/pt_13_yaml_safe_load.md
