### ISSUE TITLE
User must exist error

### ISSUE THREAD

**Issue by ramaboo** [paper-trail-gem/paper_trail#1412]
Paper trail 14 seems to break in ways I was not expecting in environments without users. Given a model

class Something
  has_paper_trail
 end
 
 Doing something simple like Something.destroy in console results in a User must exist error. This means any changes to the Something model in console or Sidekiq fail even though Something.valid?. For destroy this will cause the original Something to be destroyed but none of its dependent relationships :( A far better way would be to set user to 0 or nil rather than just dying.

**Comment by BagpipesJohnson** [comment]
I think that's why it's recommended to set `whodunnit` for whoever is running the console: https://github.com/paper-trail-gem/paper_trail/wiki/Setting-whodunnit-in-the-rails-console
