### ISSUE TITLE
changeset shows no changes，but it's created

### ISSUE THREAD

**Issue by Iiuqingshan** [paper-trail-gem/paper_trail#1430]
I configured papertrail in the ApplicationRecord, and the model will inherit the ApplicationRecord
But when I save directly without updating any properties, the version is still created

```ruby
has_paper_trail(
    # synchronize_version_creation_timestamp: false,
    on: [:update, :create, :destroy],
    ignore: [:updated_at],
    versions: { class_name: "MfaVersion" })
```

The changeset in the final generated version looks like this
```ruby
object_changes: {"announcement"=>[{}, {}]},
```

**Comment by iltempo** [comment]
Regardless of the configuration, I ran into the same issue when a record was touched. If not explicitly, it might happen, for example, when a `touch: true` relationship between models is defined.

The workaround for me was to install the callbacks manually. https://github.com/paper-trail-gem/paper_trail#controlling-the-order-of-ar-callbacks
