### ISSUE TITLE
Silenced failures on yaml parsing with an empty changeset

### ISSUE THREAD

**Issue by brymacto** [paper-trail-gem/paper_trail#1432]
https://github.com/paper-trail-gem/paper_trail/blob/eb58b5409c3e91249b869448dc10f4191834379a/lib/paper_trail/version_concern.rb#L359

When a yaml parsing error is encountered, an empty object changes object is returned with a warning logged.

Is it not better to fail fast here and let an exception surface?  The empty object is misleading and difficult to debug.

If there's openness to such a change, I could open a PR.

**Comment by gurgelrenan** [comment]
@brymacto Could you reproduce this issue following this guide? https://github.com/paper-trail-gem/paper_trail/blob/master/.github/ISSUE_TEMPLATE/bug-report.md
