### ISSUE TITLE
Support Rails 7.1

### ISSUE THREAD

**Issue by hatsu38** [paper-trail-gem/paper_trail#1442]
**Is your feature suggestion related to a problem? Please describe.**

With the recent release of Rails 7.1, it would be beneficial for this gem to be compatible with it to allow developers to take advantage of the latest features and improvements offered by Rails 7.1. 

**Describe the solution you'd like to build**

I suggest updating the gem to ensure compatibility with Rails 7.1. 
Currently they are as follows

lib/paper_trail/compatibility.rb
```ruby
ACTIVERECORD_LT = "< 7.1" # not enforced in gemspec
```

**Comment by spaquet** [comment]
that's the only thing preventing my app to be upgraded to Rails 7.1 ;-)
@hatsu38 Thanks for the proposed commit. Looking forward to having it approved soon.

**Comment by isaacbowen** [comment]
@jaredbeck 👋 🙏

**Comment by jkwuc89** [comment]
What is the status of this? It looks like we have a PR that will add Rails 7.1 support. Like @spaquet above, this is the only thing preventing my upgrade to Rails 7.1.

**Comment by StanBright** [comment]
I just did a quick review and have a minor comment that I think should be regarded before proceeding - https://github.com/paper-trail-gem/paper_trail/pull/1445/files#r1359143418

**Comment by hatsu38** [comment]
solve by : https://github.com/paper-trail-gem/paper_trail/pull/1443
