### ISSUE TITLE
Add support for Rails 7.2

### ISSUE THREAD

**Issue by rmatovu987** [paper-trail-gem/paper_trail#1488]
Thank you for your contribution!

Due to limited volunteers, issues that do not follow this template will be
closed without comment.

**Is your feature suggestion related to a problem? Please describe.**

There is a warning thrown in Rails 7.2 applications.
`PaperTrail 15.1.0 is not compatible with ActiveRecord 7.2.0. We allow PT
  contributors to install incompatible versions of ActiveRecord, and this
  warning can be silenced with an environment variable, but this is a bad
  idea for normal use. Please install a compatible version of ActiveRecord
  instead (>= 6.1, < 7.2). Please see the discussion in paper_trail/compatibility.rb
  for details.`

**Describe the solution you'd like to build**

Add support for Rails 7.2

**Describe alternatives you've considered**

N/A

**Comment by zameo94** [comment]
@rmatovu987 Thanks for opening the ticket. Yes, we definitely need compatibility with Rail 7.2

**Comment by gurgelrenan** [comment]
We have an P.R open and could be merged soon #1485

**Comment by xeron** [comment]
Could someone please clarify – besides a warning about 7.2 are there any actual incompatibilities / issues?

**Comment by fatkodima** [comment]
> Could someone please clarify – besides a warning about 7.2 are there any actual incompatibilities / issues?

It works without problems if you don't have any existing `paper_trail` warnings, because in that case it will error out (but if you fix them, it will still work), see https://github.com/paper-trail-gem/paper_trail/pull/1485/files#diff-1f8592ba4c3060dd4ee3248e4104efc57d55d350f3234cf8562a55825b949dc0R161

**Comment by kapso** [comment]
Any idea when Rails 7.2 support is going out? thanks.

**Comment by tarellel** [comment]
@kapso 

papertrail works with 7.2 its just a warning,
If you're having issues, use the patched fork of the gem until it gets approved and merged into master.

https://github.com/paper-trail-gem/paper_trail/pull/1485

**Comment by gurgelrenan** [comment]
closed by #1485
