### ISSUE TITLE
Add support for rails 8.0.0.alpha

### ISSUE THREAD

**Issue by zunair-dev** [paper-trail-gem/paper_trail#1490]
I'm facing this on `rails db:migrate`

```
PaperTrail 15.1.0 is not compatible with ActiveRecord 8.0.0.alpha. We allow PT
contributors to install incompatible versions of ActiveRecord, and this
warning can be silenced with an environment variable, but this is a bad
idea for normal use. Please install a compatible version of ActiveRecord
instead (>= 6.1, < 7.2). Please see the discussion in paper_trail/compatibility.rb
for details.
```

as obviously it supports rails <7.2
![image](https://github.com/user-attachments/assets/9b611635-a6e7-49de-90dd-e6a26041d922)

**Comment by navidemad** [comment]
There are releasing a new version only when it's not a beta neither an alpha.
You can set the environment variable for the moment
`PT_SILENCE_AR_COMPAT_WARNING=1`
But with caution cause nothing guarantees that the gem does not need adjustements.

**Comment by zunair-dev** [comment]
alrigh @navidemad, I'll suppress the warning until we get support for rails 8.
