### ISSUE TITLE
please consider taking on new maintainers

### ISSUE THREAD

**Issue by modosc** [paper-trail-gem/paper_trail#1492]
i've had a [pr](https://github.com/paper-trail-gem/paper_trail/pull/1450) open for almost a year now. it took six months for anyone to comment on it, and after i responded there was silence. the [original issue](https://github.com/paper-trail-gem/paper_trail/issues/1449) was closed as stale so i had to [reopen it](https://github.com/paper-trail-gem/paper_trail/issues/1466) and chime in regularly with unnecessary comments to keep the bots at bay.

right now a [pr](https://github.com/paper-trail-gem/paper_trail/pull/1485) to support rails 7.2 has sat for a month with (as far as i can tell) no interaction from the maintainers. 

i understand that my pr may be a niche case but adding support for a new rails release is a bare minimum level of support that users of a gem should expect.

normally neither of this issues would matter to me - i'd just fork and publish my own version (and in fact that's what i've done for my workplace).  however, this is an incredibly popular gem and having it stagnate like this is unfortunate.

please consider bringing on some new maintainers. i'm happy to volunteer to help here and i'm sure there are others too. we appreciate the work that's gone into this code and we want to see it continue on with the same high level of quality.

**Comment by tbrammar** [comment]
It looks like @gurgelrenan is a maintainer and he chipped in on the first attempt at a Rails 7.2 compatible PR, but I agree that this is a super popular Gem and needs to be able to support at the very least Rails update. Happy to help where I can

**Comment by jaredbeck** [comment]
Hi everyone, I appreciate the support. Over the past decade, I've added half a dozen members to this org, and I'd be happy to bring on another one or two people.

If you have made a contribution to this gem in the past, please nominate yourself. The project is pretty mature at this point, so I'm more inclined to invite someone who will maintain it without making many breaking changes.

**Comment by skipkayhil** [comment]
I'd like to nominate myself and/or @fatkodima (if they are willing). Both of us are on the Rails Issues Team and have a history of open source contributions which I think would make us good candidates for maintenance.

I definitely agree with your stance on avoiding many changes, and I'd be happy to do Ruby/Rails bumps as they come. I also use `paper_trail` on my Rails application at work, so I'm definitely incentivized to keep things up to date 😅

**Comment by jaredbeck** [comment]
Thank you @skipkayhil for volunteering. I've sent you and @fatkodima invitations. Please contact me by email with your preferred rubygems dot org credentials.

**Comment by jaredbeck** [comment]
@modosc I've sent you an invite too. Thanks for volunteering.

**Comment by modosc** [comment]
> @modosc I've sent you an invite too. Thanks for volunteering.

thanks! is is possible to also bring folks on as collaborators/owners (not sure the equivalent) on rubygems?

**Comment by jaredbeck** [comment]
> is is possible to also bring folks on as collaborators/owners (not sure the equivalent) on rubygems?

@modosc Yes, please contact me by email with your preferred rubygems dot org credentials. (Sorry, if you already sent them and they got lost, please send again)

Gem release instructions are here: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/CONTRIBUTING.md#releases

Thanks for the maintenance you've both been doing the past few months!
