### ISSUE TITLE
MySQL support for where_object and where_object_changes

### ISSUE THREAD

**Issue by abrieff** [paper-trail-gem/paper_trail#1496]
Thank you for your contribution!

Due to limited volunteers, issues that do not follow this template will be
closed without comment.

**Is your feature suggestion related to a problem? Please describe.**

Attempting to use where_object or where_object_changes using Mysql 8 raises an error, for example:

```
PaperTrail::Version Load (23.0ms)  SELECT `versions`.* FROM `versions` WHERE `versions`.`item_type` = 'CustomPrice' AND (((object_changes->>'canonical_institution_id' ILIKE '[1,%') OR (object_changes->>'canonical_institution_id' ILIKE '[%,1]%')))
```
is not valid mysql.

**Describe the solution you'd like to build**

The where_object and where_object_changes functions should support both MySQL and PostgreSQL.

**Describe alternatives you've considered**

This can be hacked around using plain MySQL syntax, but it would be great to be able to use the included helper methods.

**Comment by gurgelrenan** [comment]
Hi @abrieff . Could you please follow the issue template described here: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/CONTRIBUTING.md#reporting-bugs in order to open an issue? Thanks!
